/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jReceber.java
 *
 * Created on 16/03/2011, 14:40:15
 */

package Transicao;

import Funcoes.Dates;
import Funcoes.DbMain;
import Funcoes.FuncoesGlobais;
import Funcoes.LerValor;
import Funcoes.VariaveisGlobais;
import Sicit.Login.JNABalloon;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;

/**
 *
 * @author supervisor
 */
public class jPagarExtrato extends javax.swing.JPanel {
    public static String vrDOCTO = "0,00";
    private int tpOPC  = 0;
    public float vrAREC = 0;
    private boolean jbt = true;
    public boolean bprintdoc = false;
    public String rgprp = "", rgimv = "", contrato = "", operacao = "DEB", acao = "";
    static DbMain conn = VariaveisGlobais.conexao;
    float maxch = 0;
    
    /** Creates new form jReceber */
    public jPagarExtrato() {
        initComponents();

        //jtgCT.setVisible(false);
        //jlbCT.setVisible(false);
        
        // carrega limite do cheque
        try {maxch = LerValor.StringToFloat(LerValor.FormatNumber(conn.LerParametros("MAXCH"),2));} catch (Exception ex) {maxch = 0;}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGrupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jfmCT = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jfmBC = new javax.swing.JFormattedTextField(3);
        jLabel7 = new javax.swing.JLabel();
        jfmAG = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jfmCH = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jfmDT = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
        jLabel10 = new javax.swing.JLabel();
        jfmVRCH = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jfmVRDN = new javax.swing.JFormattedTextField();
        jbtLancar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jRESTO = new javax.swing.JFormattedTextField();
        jTROCO = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtgDN = new javax.swing.JToggleButton();
        jlbDN = new javax.swing.JLabel();
        jtgCH = new javax.swing.JToggleButton();
        jlbCH = new javax.swing.JLabel();
        jtgCT = new javax.swing.JToggleButton();
        jlbCT = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(414, 413));

        jPanel1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jPanel1.setName("jpnDigite"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(385, 280));

        jLabel5.setText("Número:");

        jfmCT.setEnabled(false);

        jLabel6.setText("Banco:");

        jfmBC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("000"))));
        jfmBC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfmBC.setText("000");
        jfmBC.setEnabled(false);
        jfmBC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jfmBCFocusLost(evt);
            }
        });

        jLabel7.setText("Agência:");

        jfmAG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0000"))));
        jfmAG.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfmAG.setText("0000");
        jfmAG.setEnabled(false);

        jLabel8.setText("Cheque:");

        jfmCH.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("000000"))));
        jfmCH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfmCH.setText("000000");
        jfmCH.setEnabled(false);

        jLabel9.setText("Dt:");

        jfmDT.setDate(new java.util.Date(-2208977612000L));
        jfmDT.setEnabled(false);

        jLabel10.setText("Valor Cheque:");

        jfmVRCH.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jfmVRCH.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jfmVRCH.setText("0,00");
        jfmVRCH.setEnabled(false);
        jfmVRCH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jfmVRCHFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jfmVRCHFocusLost(evt);
            }
        });

        jLabel11.setText("Valor Dinheiro:");

        jfmVRDN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jfmVRDN.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jfmVRDN.setText("0,00");
        jfmVRDN.setEnabled(false);
        jfmVRDN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jfmVRDNFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jfmVRDNFocusLost(evt);
            }
        });

        jbtLancar.setText("Lançar");
        jbtLancar.setName("jbtLancar"); // NOI18N

        jbtCancelar.setText("Cancelar");
        jbtCancelar.setName("jbtCancelar"); // NOI18N

        jLabel12.setText("RESTA:");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setText("TROCO:");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jRESTO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jRESTO.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jRESTO.setText("0,00");
        jRESTO.setDisabledTextColor(new java.awt.Color(51, 153, 0));
        jRESTO.setEnabled(false);
        jRESTO.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRESTO.setName("jRESTO"); // NOI18N
        jRESTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRESTOActionPerformed(evt);
            }
        });

        jTROCO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jTROCO.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTROCO.setText("0,00");
        jTROCO.setDisabledTextColor(new java.awt.Color(255, 0, 51));
        jTROCO.setEnabled(false);
        jTROCO.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jLabel14.setBackground(new java.awt.Color(204, 204, 255));
        jLabel14.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Digite");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel14.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jfmBC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jfmAG, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(104, 104, 104)
                                                .addComponent(jfmVRCH))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(55, 55, 55)
                                                        .addComponent(jfmCH, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel8))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9)
                                                .addGap(3, 3, 3)
                                                .addComponent(jfmDT, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel10))
                                    .addGap(7, 7, 7)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jfmVRDN))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtLancar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jfmCT)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTROCO, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRESTO, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfmCT, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfmBC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfmAG, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jfmCH, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfmDT, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfmVRCH, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfmVRDN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtLancar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRESTO, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTROCO, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setName("pnlBotoes"); // NOI18N

        jtgDN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_dn_bw.jpg"))); // NOI18N
        jtgDN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtgDN.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_dn_bw.jpg"))); // NOI18N
        jtgDN.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_dn_bw.jpg"))); // NOI18N
        jtgDN.setName("jtgDN"); // NOI18N
        jtgDN.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_dn.jpg"))); // NOI18N
        jtgDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtgDNActionPerformed(evt);
            }
        });

        jlbDN.setBackground(java.awt.Color.white);
        jlbDN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbDN.setText("Dinheiro");
        jlbDN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jlbDN.setOpaque(true);

        jtgCH.setBackground(java.awt.Color.white);
        jtgCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_ch_bw.jpg"))); // NOI18N
        jtgCH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtgCH.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_ch_bw.jpg"))); // NOI18N
        jtgCH.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_ch_bw.jpg"))); // NOI18N
        jtgCH.setName("jtgCH"); // NOI18N
        jtgCH.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_ch.jpg"))); // NOI18N
        jtgCH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtgCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtgCHActionPerformed(evt);
            }
        });

        jlbCH.setBackground(java.awt.Color.white);
        jlbCH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCH.setText("Cheque");
        jlbCH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jlbCH.setOpaque(true);

        jtgCT.setBackground(java.awt.Color.white);
        jtgCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_ct_bw.jpg"))); // NOI18N
        jtgCT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtgCT.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_ct_bw.jpg"))); // NOI18N
        jtgCT.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_ct_bw.jpg"))); // NOI18N
        jtgCT.setName("jtgCT"); // NOI18N
        jtgCT.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ico_ct.jpg"))); // NOI18N
        jtgCT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtgCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtgCTActionPerformed(evt);
            }
        });

        jlbCT.setBackground(java.awt.Color.white);
        jlbCT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCT.setText("Banco");
        jlbCT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jlbCT.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlbDN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtgDN, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbCH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtgCH))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtgCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtgCT, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jtgCH, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jtgDN, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbDN)
                    .addComponent(jlbCH)
                    .addComponent(jlbCT)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, 0, 302, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 302, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jfmVRCHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfmVRCHFocusGained
        float result = (LerValor.StringToFloat(jTROCO.getText()) * -1) + LerValor.StringToFloat(jRESTO.getText()) + LerValor.StringToFloat(jfmVRCH.getText());
        jRESTO.setValue(result);
        jTROCO.setValue(0);

        FuncoesGlobais.SelectAllInFormattedTextField(evt);
}//GEN-LAST:event_jfmVRCHFocusGained

    private void jfmVRCHFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfmVRCHFocusLost
        jbtLancar.setEnabled(LerValor.StringToFloat(jfmVRCH.getText()) >= 0);
        // Checa se o valor ultrapassou o limite
        float le_ch = LerValor.StringToFloat(jfmVRCH.getText());        
        if (le_ch > maxch) {
            final String BALLOON_TEXT = "<html><center>"
                    + "Limite por cheque atingido!!!<BR>Limite por cheque <BR><font color=red>NÃO</font> pode ser superior a <BR>" + LerValor.FloatToString(maxch) + "<br>"
                    + "(Click para desaparecer este balloon)</center></html>";
            JNABalloon balloon = new JNABalloon(BALLOON_TEXT, jfmVRCH, 0, 5);
            balloon.showBalloon();
            
            jbtLancar.setEnabled(false);
            jTROCO.setValue(le_ch);
            jRESTO.setValue(0);
            jfmVRCH.requestFocus();
            return;
        } else jbtLancar.setEnabled(true);
        
        float result = LerValor.StringToFloat(jRESTO.getText()) - LerValor.StringToFloat(jfmVRCH.getText());
        if (result < 0) {
            final String BALLOON_TEXT = "<html><center>"
                    + "Lançamentos em Cheque <font color=red>NÃO</font> PODEM GERAR TROCO...<br>"
                    + "(Click para desaparecer este balloon)</center></html>";
            JNABalloon balloon = new JNABalloon(BALLOON_TEXT, jfmVRCH, 0, 5);
            balloon.showBalloon();
            
            jbtLancar.setEnabled(false);
            jTROCO.setValue(result * -1);
            jRESTO.setValue(0);
            jfmVRCH.requestFocus();
        } else { jRESTO.setValue(result); jTROCO.setValue(0); jbtLancar.setEnabled(true);}
}//GEN-LAST:event_jfmVRCHFocusLost

    private void jfmVRDNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfmVRDNFocusGained
        float result = (LerValor.StringToFloat(jTROCO.getText()) * -1) + LerValor.StringToFloat(jRESTO.getText()) + LerValor.StringToFloat(jfmVRDN.getText());
        jRESTO.setValue(result);
        jTROCO.setValue(0);

        FuncoesGlobais.SelectAllInFormattedTextField(evt);
}//GEN-LAST:event_jfmVRDNFocusGained

    private void jfmVRDNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfmVRDNFocusLost
        jbtLancar.setEnabled(LerValor.StringToFloat(jfmVRDN.getText()) >= 0);
        float result = LerValor.StringToFloat(jRESTO.getText()) - LerValor.StringToFloat(jfmVRDN.getText());
        if (result < 0) {
            jTROCO.setValue(result * -1);
            jRESTO.setValue(0);
            if (tpOPC == 3) {
                final String BALLOON_TEXT = "<html><center>"
                        + "Lançamentos em CARTÃO <font color=red>NÃO</font> PODEM GERAR TROCO...<br>"
                        + "(Click para desaparecer este balloon)</center></html>";
                JNABalloon balloon = new JNABalloon(BALLOON_TEXT, jfmVRCH, 0, 5);
                balloon.showBalloon();
                
                jbtLancar.setEnabled(false);
                jfmVRDN.requestFocus();
            }
        } else { jRESTO.setValue(result); jTROCO.setValue(0); jbtLancar.setEnabled(true);}
}//GEN-LAST:event_jfmVRDNFocusLost

    private void jtgDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtgDNActionPerformed
        Escolha(1);
}//GEN-LAST:event_jtgDNActionPerformed

    private void jtgCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtgCHActionPerformed
        Escolha(2);
}//GEN-LAST:event_jtgCHActionPerformed

    private void jtgCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtgCTActionPerformed
        Escolha(3);
}//GEN-LAST:event_jtgCTActionPerformed

    private void jRESTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRESTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRESTOActionPerformed

    private void jfmBCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfmBCFocusLost
        if (jfmBC.getText().length() == 34) {
            String campo = jfmBC.getText();
            String bco = campo.substring(1,4);
            String age = campo.substring(4,8);
            String nch = campo.substring(13,19);
            
            jfmBC.setText(bco);
            jfmAG.setText(age);
            jfmCH.setText(nch);
            
            //jfmCH.requestFocus();
            //jfmDT.requestFocus();
            
            String smaxch = LerValor.FloatToString(maxch);
            float le_resta = LerValor.StringToFloat(jRESTO.getText());
            if (le_resta <= maxch) {
                jfmVRCH.setText(LerValor.FloatToString(le_resta));
                jRESTO.setText("0,00");
            } else {
                jfmVRCH.setText(smaxch);
                jRESTO.setValue(LerValor.StringToFloat(jRESTO.getText()) - maxch);
            }
            jfmVRCH.selectAll();
            jfmVRCH.requestFocus();
        }        
    }//GEN-LAST:event_jfmBCFocusLost

    public void Lancar() {
        float result = LerValor.StringToFloat(jRESTO.getText());
        float digitar = 0;
        if (tpOPC == 1) { digitar = LerValor.StringToFloat(jfmVRDN.getText()); }
        if (tpOPC == 2) { digitar = LerValor.StringToFloat(jfmVRCH.getText()); }
        if (tpOPC == 3) { digitar = LerValor.StringToFloat(jfmVRDN.getText()); }

        //if (digitar > 0) {
            String sqlTxt = "INSERT INTO Transicao (rgprp, rgimv, contrato, ncaixa, tipo, data, datapre, cartao, banco, " +
                         "agencia, cheque, vrcheque, vrdinheiro, operacao, acao) " +
                         "VALUES ('&1.','&2.','&3.','&4.','&5.','&6.','&7.','&8.','&9.','&10.','&11.','&12.','&13.','&14.','&15.')";

//            String dnLancar = LerValor.floatToCurrency(LerValor.StringToFloat(jfmVRDN.getText()) - LerValor.StringToFloat(jTROCO.getText()),2);
//            String dtpre = (jfmDT.getDate() == null ? "" : Dates.DateFormata("dd/MM/yyyy", jfmDT.getDate()));
            String dtpre = (jfmDT.getDate() == null ? "" : Dates.DateFormata("dd/MM/yyyy", jfmDT.getDate()));
            String dnLancar = LerValor.floatToCurrency(LerValor.StringToFloat(jfmVRDN.getText()) - LerValor.StringToFloat(jTROCO.getText()),2);

//            sqlTxt = FuncoesGlobais.Subst(sqlTxt, new String[] {
//                      rgprp,
//                      rgimv,
//                      contrato,
//                      VariaveisGlobais.usuario,
//                      (tpOPC == 1 ? "DN" : (tpOPC == 2 ? "CH" : "CT")),
//                      Dates.DateFormata("dd/MM/yyyy", new Date()),
//                      dtpre,
//                      jfmCT.getText().trim(),
//                      jfmBC.getText(), jfmAG.getText(), jfmCH.getText(),
//                      FuncoesGlobais.GravaValores(jfmVRCH.getText(),2),
//                      dnLancar,
//                      operacao, acao});
        sqlTxt = FuncoesGlobais.Subst(sqlTxt, new String[] {
                  rgprp,
                  rgimv,
                  contrato,
                  VariaveisGlobais.usuario,
                  (tpOPC == 1 ? "DN" : (tpOPC == 2 ? ("".equals(dtpre) ? "CH" : "CP") : "CT")),
                  Dates.DateFormata("dd/MM/yyyy", new Date()),
                  dtpre,
                  jfmCT.getText().trim(),
                  jfmBC.getText(), jfmAG.getText(), jfmCH.getText(),
                  FuncoesGlobais.GravaValores(jfmVRCH.getText(),2),
                  FuncoesGlobais.GravaValores(dnLancar,2),
                  operacao, acao});

            conn.ExecutarComando(sqlTxt);
        //}

        if (result > 0 && digitar > 0) {
            if (tpOPC == 1) { jfmVRDN.setValue(0); jfmVRDN.requestFocus(); } else
            if (tpOPC == 2) { jfmBC.setText("");   jfmAG.setText(""); jfmCH.setText(""); jfmVRCH.setValue(0); jfmBC.requestFocus(); } else
            if (tpOPC == 3) { jfmVRDN.setValue(0); jfmCT.setText(""); jfmCT.requestFocus(); }

            bprintdoc = false;
        } else {
            bprintdoc = true;
        }
    }

    public void LimpaTransicao() {
        String[] param = {VariaveisGlobais.usuario.trim(), acao};
        String sql = FuncoesGlobais.Subst("DELETE FROM Transicao WHERE ncaixa = '&1.' AND acao = '&2.';", param);
        conn.ExecutarComando(sql);
    }

    public boolean Cancelar() {
        boolean retorno = false;
        if (jbt) {
            Escolha(4);
            jRESTO.setValue(vrAREC); jTROCO.setValue(0);
            jbtCancelar.setEnabled(true);
            jbtLancar.setEnabled(false);
            bprintdoc = false;
            LimpaTransicao();
            retorno = true;
        } else {
            //if (LerValor.StringToFloat(jfmVRCH.getText()) + LerValor.StringToFloat(jfmVRDN.getText()) == 0)  {
                float result = (LerValor.StringToFloat(jTROCO.getText()) * -1) + LerValor.StringToFloat(jRESTO.getText()) + LerValor.StringToFloat(jfmVRDN.getText()) + LerValor.StringToFloat(jfmVRCH.getText());
                jRESTO.setValue(result);
                jTROCO.setValue(0);

                jbt = true;
                Enable(false);
                btEnabled(true);
                jbtCancelar.setEnabled(true);
                retorno = false;
            //}
        }
        return retorno;
    }

    public void Enable(boolean enb) {
        if (!enb) {
            jfmCT.setEnabled(enb);
            jfmCT.setText("");
            jfmBC.setEnabled(enb);
            jfmBC.setText("");
            jfmAG.setEnabled(enb);
            jfmAG.setText("");
            jfmCH.setEnabled(enb);
            jfmCH.setText("");
            jfmDT.setEnabled(enb);
            jfmDT.setDate(null);
            jfmVRCH.setEnabled(enb);
            jfmVRCH.setValue(0);
            jfmVRDN.setEnabled(enb);
            jfmVRDN.setValue(0);
        }
        jtgDN.setEnabled(enb);
        jtgCH.setEnabled(enb);
        jtgCT.setEnabled(enb);
        jbtLancar.setEnabled(enb);
        jbtCancelar.setEnabled(enb);
    }

    public void Clear() {
        jfmCT.setText("");
        jfmBC.setText("");
        jfmAG.setText("");
        jfmCH.setText("");
        jfmDT.setDate(null);
        jfmVRCH.setValue(0);
        jfmVRDN.setValue(0);
        jRESTO.setText("0,00");
        jTROCO.setText("0,00");
    }

    private void btEnabled(boolean enb) {
        jtgDN.setEnabled(enb);
        jtgCH.setEnabled(enb);
        jtgCT.setEnabled(enb);
        jbtLancar.setEnabled(!enb);
        jbtCancelar.setEnabled(!enb);
    }

    public void Escolha(int tipo) {
        if (tipo == 1) {
                jlbDN.setBackground(Color.red);
                jlbDN.setForeground(Color.yellow);

                jlbCH.setBackground(Color.white);
                jlbCH.setForeground(Color.black);

                jlbCT.setBackground(Color.white);
                jlbCT.setForeground(Color.black);

                jfmCT.setEnabled(false);
                jfmCT.setText("");
                jfmBC.setEnabled(false);
                jfmBC.setText("");
                jfmAG.setEnabled(false);
                jfmAG.setText("");
                jfmCH.setEnabled(false);
                jfmCH.setText("");
                jfmDT.setEnabled(false);
                jfmDT.setDate(null);
                jfmVRCH.setEnabled(false);
                jfmVRCH.setValue(0);

                jfmVRDN.setEnabled(true);
                jfmVRDN.setValue(0);
                jfmVRDN.requestFocus();

        } else if (tipo == 2) {
                jlbDN.setBackground(Color.white);
                jlbDN.setForeground(Color.black);

                jlbCH.setBackground(Color.red);
                jlbCH.setForeground(Color.yellow);

                jlbCT.setBackground(Color.white);
                jlbCT.setForeground(Color.black);

                jfmCT.setEnabled(false);
                jfmCT.setText("");
                jfmVRDN.setEnabled(false);
                jfmVRDN.setValue(0);

                jfmBC.setEnabled(true);
                jfmBC.setText("");
                jfmAG.setEnabled(true);
                jfmAG.setText("");
                jfmCH.setEnabled(true);
                jfmCH.setText("");
                jfmDT.setEnabled(true);
                jfmDT.setDate(null);
                jfmVRCH.setEnabled(true);
                jfmVRCH.setValue(0);
               jfmBC.requestFocus();

        } else if (tipo == 3) {
                jlbDN.setBackground(Color.white);
                jlbDN.setForeground(Color.black);

                jlbCH.setBackground(Color.white);
                jlbCH.setForeground(Color.black);

                jlbCT.setBackground(Color.red);
                jlbCT.setForeground(Color.yellow);

                jfmBC.setEnabled(false);
                jfmBC.setText("");
                jfmAG.setEnabled(false);
                jfmAG.setText("");
                jfmCH.setEnabled(false);
                jfmCH.setText("");
                jfmDT.setEnabled(false);
                jfmDT.setDate(null);
                jfmVRCH.setEnabled(false);
                jfmVRCH.setValue(0);

                jfmCT.setEnabled(true);
                jfmCT.setText("");
                jfmVRDN.setEnabled(true);
                jfmVRDN.setValue(0);
                jfmCT.requestFocus();
        } else {
                jlbDN.setBackground(Color.white);
                jlbDN.setForeground(Color.black);
                jtgDN.setSelected(false);

                jlbCH.setBackground(Color.white);
                jlbCH.setForeground(Color.black);
                jtgCH.setSelected(false);

                jlbCT.setBackground(Color.white);
                jlbCT.setForeground(Color.black);
                jtgCT.setSelected(false);

                jfmBC.setEnabled(false);
                jfmBC.setText("");
                jfmAG.setEnabled(false);
                jfmAG.setText("");
                jfmCH.setEnabled(false);
                jfmCH.setText("");
                jfmDT.setEnabled(false);
                jfmDT.setDate(null);
                jfmVRCH.setEnabled(false);
                jfmVRCH.setValue(0);

                jfmCT.setEnabled(false);
                jfmCT.setText("");
                jfmVRDN.setEnabled(false);
                jfmVRDN.setValue(0);
        }

        tpOPC = tipo;

        if (tipo < 4) {Enable(true); btEnabled(false); jbt = false;}
    }

    public String[][] Transicao(String acao) throws SQLException {
        String sql = "SELECT data, tipo, operacao, acao, cartao, datapre, banco, agencia, cheque, SUM(`" +
                VariaveisGlobais.dbnome +
                "`.`StrVal`(vrdinheiro)) vrdinheiro, SUM(`" + VariaveisGlobais.dbnome +
                "`.`StrVal`(vrcheque)) vrcheque FROM Transicao WHERE Lower(ncaixa) = '&1.' AND acao = '&2.' AND data = '&3.' GROUP BY banco, agencia, cheque;";
        sql = FuncoesGlobais.Subst(sql, new String[] {VariaveisGlobais.usuario.toLowerCase(), acao.toUpperCase(), Dates.DateFormata("dd/MM/yyyy", new Date())});
        ResultSet rs = conn.AbrirTabela(sql, ResultSet.CONCUR_READ_ONLY);
        String[][] retorno = {};

        while (rs.next()) {
            String stipo = rs.getString("tipo");
            String soper = rs.getString("operacao");
            String sacao = rs.getString("acao");
            String scartao = rs.getString("cartao");
            String sdtpre = rs.getString("datapre");
            String sbanco = rs.getString("banco");
            String sagencia = rs.getString("agencia");
            String scheque = rs.getString("cheque");

            String svrdinheiro = rs.getString("vrdinheiro");
            String svrcheque = rs.getString("vrcheque");

            retorno = FuncoesGlobais.ArraysAdd(retorno, new String[]
                    {sdtpre, sbanco,sagencia, scheque,
                    (rs.getFloat("vrdinheiro") > 0 ? svrdinheiro : svrcheque),
                    stipo, soper, sacao, scartao});
        }

        DbMain.FecharTabela(rs);
        return retorno;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jGrupo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFormattedTextField jRESTO;
    private javax.swing.JFormattedTextField jTROCO;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtLancar;
    private javax.swing.JFormattedTextField jfmAG;
    private javax.swing.JFormattedTextField jfmBC;
    private javax.swing.JFormattedTextField jfmCH;
    private javax.swing.JFormattedTextField jfmCT;
    private com.toedter.calendar.JDateChooser jfmDT;
    private javax.swing.JFormattedTextField jfmVRCH;
    private javax.swing.JFormattedTextField jfmVRDN;
    private javax.swing.JLabel jlbCH;
    private javax.swing.JLabel jlbCT;
    private javax.swing.JLabel jlbDN;
    private javax.swing.JToggleButton jtgCH;
    private javax.swing.JToggleButton jtgCT;
    private javax.swing.JToggleButton jtgDN;
    // End of variables declaration//GEN-END:variables

}
