/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sici.Partida;

import Funcoes.CentralizaTela;
import Funcoes.Dates;
import Funcoes.DbMain;
import Funcoes.FuncoesGlobais;
import Funcoes.TableControl;
import Funcoes.VariaveisGlobais;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JInternalFrame;
import java.lang.reflect.Method;
import javax.swing.ImageIcon;

/**
 *
 * @author softeletronic
 */
public class jBuscaGlobalizada extends javax.swing.JInternalFrame {
    DbMain conn = VariaveisGlobais.conexao;

    /**
     * Creates new form jBuscaGlobalizada
     */
    public jBuscaGlobalizada() {
        initComponents();
        
        ImageIcon icone = new ImageIcon("/Figuras/seach.png");
        setFrameIcon(icone);
        
        VariaveisGlobais.jBuscar.addFocusListener(new FocusListener() {
            public void focusGained(FocusEvent e) {
                if (VariaveisGlobais.jBuscar.getText().trim().equals("")) TableControl.Clear(jtbBuscas);
                int xpos = VariaveisGlobais.jPanePrin.getWidth() - getWidth();
                int ypos = 40;
                setLocation(xpos, ypos);
                setVisible(true);
                VariaveisGlobais.jBuscar.requestFocus();
            };
            public void focusLost(FocusEvent e) {}
        });
        
        VariaveisGlobais.jBuscar.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {}

            @Override
            public void keyPressed(KeyEvent e) {}

            @Override
            public void keyReleased(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
                    setVisible(false);
                    return;
                }

                Buscar();
                setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jrbProp = new javax.swing.JRadioButton();
        jrbLoca = new javax.swing.JRadioButton();
        jrbImoveis = new javax.swing.JRadioButton();
        jrbFiadores = new javax.swing.JRadioButton();
        jcbHeuristica = new javax.swing.JCheckBox();
        jInativos = new javax.swing.JCheckBox();
        jrbboletas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbBuscas = new javax.swing.JTable();

        setTitle(".:: Busca Global");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Critérios da busca:"));
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N

        buttonGroup1.add(jrbProp);
        jrbProp.setSelected(true);
        jrbProp.setText("Proprietários");
        jrbProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPropActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbLoca);
        jrbLoca.setText("Locatários");
        jrbLoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbLocaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbImoveis);
        jrbImoveis.setText("Imóveis");
        jrbImoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbImoveisActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbFiadores);
        jrbFiadores.setText("Fiadores");
        jrbFiadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFiadoresActionPerformed(evt);
            }
        });

        jcbHeuristica.setSelected(true);
        jcbHeuristica.setText("Buscar em qualquer posição");
        jcbHeuristica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHeuristicaActionPerformed(evt);
            }
        });

        jInativos.setText("Desativados");
        jInativos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInativosActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbboletas);
        jrbboletas.setText("Boletas");
        jrbboletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbboletasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jInativos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbHeuristica, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jrbProp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbLoca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbImoveis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbFiadores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrbboletas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbHeuristica)
                    .addComponent(jInativos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbProp)
                    .addComponent(jrbLoca)
                    .addComponent(jrbImoveis)
                    .addComponent(jrbFiadores)
                    .addComponent(jrbboletas)))
        );

        jtbBuscas.setAutoCreateRowSorter(true);
        jtbBuscas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtbBuscas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtbBuscas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtbBuscas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbBuscasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbBuscas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPropActionPerformed
        TableControl.header(jtbBuscas, new String[][] {{"rgprp", "nome", "telefone", "cpf/cnpj", "endereço de correspondência"},{"80","500","120","150","500"}});
        VariaveisGlobais.jBuscar.requestFocus();
        Buscar();
    }//GEN-LAST:event_jrbPropActionPerformed

    private void jrbLocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbLocaActionPerformed
        TableControl.header(jtbBuscas, new String[][] {{"contrato", "rgimv", "cpf/cnpj", "nome", "endereço", "endereço de correspondência"},{"80","80","150","500","500","500"}});
        VariaveisGlobais.jBuscar.requestFocus();
        Buscar();
    }//GEN-LAST:event_jrbLocaActionPerformed

    private void jrbImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbImoveisActionPerformed
        TableControl.header(jtbBuscas, new String[][] {{"rgprp", "rgimv", "endereço"},{"80","80","500"}});
        Buscar();
        VariaveisGlobais.jBuscar.requestFocus();
    }//GEN-LAST:event_jrbImoveisActionPerformed

    private void jrbFiadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFiadoresActionPerformed
        TableControl.header(jtbBuscas, new String[][] {{"contrato", "rgimv", "nome", "cpf/cnpj"},{"80","80","500","150"}});
        Buscar();
        VariaveisGlobais.jBuscar.requestFocus();
    }//GEN-LAST:event_jrbFiadoresActionPerformed

    private void jcbHeuristicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHeuristicaActionPerformed
        Buscar();
        VariaveisGlobais.jBuscar.requestFocus();
    }//GEN-LAST:event_jcbHeuristicaActionPerformed

    private void jInativosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInativosActionPerformed
        Buscar();
        VariaveisGlobais.jBuscar.requestFocus();
        
    }//GEN-LAST:event_jInativosActionPerformed

    private void jrbboletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbboletasActionPerformed
        TableControl.header(jtbBuscas, new String[][] {{"contrato", "rgimv", "nome", "cpf/cnpj", "vencimento", "tag"},{"80","80","500","150","80","10"}});
        Buscar();
        VariaveisGlobais.jBuscar.requestFocus();
    }//GEN-LAST:event_jrbboletasActionPerformed

    private void jtbBuscasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbBuscasMouseClicked
        if (evt.getClickCount() == 2) {
            int selRow = jtbBuscas.getSelectedRow();
            Object valor = null;
            if (selRow > -1) valor = jtbBuscas.getModel().getValueAt(selRow, 0);
            String _class = ""; String _method = ""; String[] _args = {};
            if (jrbProp.isSelected() || jrbImoveis.isSelected()) {
                _class = "Sici.jProprietarios";
                _method = "MoveToProp";
                _args = new String[] {"rgprp", valor.toString()};
            } else if (jrbLoca.isSelected() || jrbFiadores.isSelected()) {
                _class = "Sici.Locatarios.jLocatarios";
                _method = "MoveToLoca";
                _args = new String[] {"contrato", valor.toString()};
            }
            try {
                Class classe = null;
                classe = Class.forName(_class);
                JInternalFrame frame = (JInternalFrame) classe.newInstance();

                Class[] args1 = new Class[2];
                args1[0] = String.class;
                args1[1] = String.class;
                Method mtd = classe.getMethod(_method, args1);
                mtd.invoke(frame, _args);

                VariaveisGlobais.jPanePrin.add(frame);
                CentralizaTela.setCentro(frame, VariaveisGlobais.jPanePrin, 0, 0);

                VariaveisGlobais.jPanePrin.getDesktopManager().activateFrame(frame);
                frame.requestFocus();
                frame.setSelected(true);
                frame.setVisible(true);
            } catch (Exception e) {e.printStackTrace();}

            VariaveisGlobais.jBuscar.setText("");
            setVisible(false);
        }
    }//GEN-LAST:event_jtbBuscasMouseClicked

    private void Buscar() {
        String[] gbProp = {"p.rgprp", "p.nome", "p.tel", "p.cpfcnpj", "p.cor_end"};
        String[] gbLoca = {"l.contrato", "l.rgimv", "l.cpfcnpj", "l.nomerazao", "l.end", "l.cor_end"};
        String[] gbImvl = {"i.rgprp", "i.rgimv", "i.end", "i.num", "i.compl", "i.situacao", "i.matriculas"};
        String[] gbFiad = {"f.nomerazao", "f.contrato", "f.rgimv", "f.cpfcnpj"};
        //String[] gbBole = {"b.nnumero", "b.contrato", "b.nome","b.vencimento","b.valor"};
        String[] gbBole = {"r.nnumero", "r.contrato", "(SELECT l.nomerazao FROM locatarios l WHERE l.contrato = r.contrato) AS nomerazao", "r.dtvencimento", "r.tag"};
        String cSql = "";
        String sBusca = VariaveisGlobais.jBuscar.getText().trim().toLowerCase();

        if(sBusca.equals("")) {
            TableControl.Clear(jtbBuscas);
            return;
        } 
            
        if (jrbProp.isSelected()) {
            String sInativos = "";
            if (!jInativos.isSelected()) {
                sInativos = "(Lower(Trim(p.status)) = 'ativo') AND (";
                VariaveisGlobais.IProp = false;
            } else {
                sInativos = "(Lower(Trim(p.status)) <> 'ativo') AND (";
                VariaveisGlobais.IProp = true;
            }
            String jgbProp = FuncoesGlobais.join(gbProp, ",");
            cSql =  "SELECT " + jgbProp + " FROM proprietarios p WHERE " + sInativos + gbProp[0].toLowerCase() + (jcbHeuristica.isSelected() ? " LIKE '%" : " LIKE '") + sBusca + "%' OR " +
            gbProp[1].toLowerCase() + (jcbHeuristica.isSelected() ? " LIKE '%" : " LIKE '") + sBusca + "%' OR " + gbProp[2].toLowerCase() + (jcbHeuristica.isSelected() ? " LIKE '%" : " LIKE '") + sBusca + "%' OR " +
            gbProp[3].toLowerCase() + (jcbHeuristica.isSelected() ? " LIKE '%" : " LIKE '") + sBusca + "%' OR " + gbProp[4].toLowerCase() + (jcbHeuristica.isSelected() ? " LIKE '%" : " LIKE '") + sBusca + "%')";

            TableControl.header(jtbBuscas, new String[][] {{"rgprp", "nome", "telefone", "cpf/cnpj", "endereço de correspondência"},{"80","500","120","150","500"}});
            ResultSet pResult = conn.AbrirTabela(cSql, ResultSet.CONCUR_READ_ONLY);
            try {
                while (pResult.next()) {
                    String trgprp = String.valueOf(pResult.getInt("p.rgprp"));
                    String tnome = pResult.getString("p.nome").toUpperCase();

                    String ttel = "";                    
                    String[] telef = null;
                    try { telef = pResult.getString("p.tel").split(";"); } catch (Exception e) {}
                    if (telef != null) {
                        for (int w=0;w<telef.length;w++) {
                            if (!telef[w].trim().equalsIgnoreCase("")) {
                                String[] tmptel = telef[w].split(",");

                                String teltmp = tmptel[0];
                                if (tmptel.length > 1) teltmp += " * " + tmptel[1];
                                ttel += teltmp + " / ";
                            }
                        }
                        if (ttel.length() > 0) ttel = ttel.substring(0, ttel.length() -3);
                    }

                    String tcpfcnpj = pResult.getString("p.cpfcnpj");
                    String tend = pResult.getString("p.cor_end");
                    TableControl.add(jtbBuscas, new String[][]{{trgprp, tnome, ttel, tcpfcnpj, tend},{"C","L","C","C","L"}},true);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            DbMain.FecharTabela(pResult);

        } else if (jrbLoca.isSelected()) {
            String sInativos = "";
            if (!jInativos.isSelected()) {
                sInativos = "(l.fiador1uf <> 'X' OR IsNull(l.fiador1uf)) AND (";
                VariaveisGlobais.Iloca = false;
            } else {
                sInativos = "(l.fiador1uf = 'X') AND (";
                VariaveisGlobais.Iloca = true;
            }
            cSql = "SELECT " + FuncoesGlobais.join(gbLoca,",") + " FROM locatarios l WHERE " + sInativos + gbLoca[0].toLowerCase() + (jcbHeuristica.isSelected() ? " LIKE '%" : " LIKE '") + sBusca + "%' OR " +
            gbLoca[1].toLowerCase() + (jcbHeuristica.isSelected() ? " LIKE '%" : " LIKE '") + sBusca + "%' OR " + gbLoca[2].toLowerCase() + (jcbHeuristica.isSelected() ? " LIKE '%" : " LIKE '") + sBusca + "%' OR " +
            gbLoca[3].toLowerCase() + (jcbHeuristica.isSelected() ? " LIKE '%" : " LIKE '") + sBusca + "%' OR " + gbLoca[4].toLowerCase() + (jcbHeuristica.isSelected() ? " LIKE '%" : " LIKE '") + sBusca + "%' OR " +
            gbLoca[5].toLowerCase() + (jcbHeuristica.isSelected() ? " LIKE '%" : " LIKE '") + sBusca + "%')";

            TableControl.header(jtbBuscas, new String[][] {{"contrato", "rgimv", "cpf/cnpj", "nome", "endereço", "endereço de correspondência"},{"80","80","150","500","500","500"}});
            ResultSet pResult = this.conn.AbrirTabela(cSql, ResultSet.CONCUR_READ_ONLY);
            try {
                while (pResult.next()) {
                    String tcontrato = String.valueOf(pResult.getInt("l.contrato"));
                    String trgimv = String.valueOf(pResult.getInt("l.rgimv"));
                    String tcpfcnpj = pResult.getString("l.cpfcnpj");
                    String tnome = pResult.getString("l.nomerazao").toUpperCase();
                    String tend = pResult.getString("l.end").toUpperCase().trim();
                    String tendcor = pResult.getString("l.cor_end").toUpperCase().trim();
                    TableControl.add(jtbBuscas, new String[][]{{tcontrato, trgimv, tcpfcnpj, tnome, tend, tendcor},{"C","C","C","L","L","L"}},true);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            DbMain.FecharTabela(pResult);

        } else if (jrbImoveis.isSelected()) {
            String sInativos = "";
            cSql = "SELECT " + FuncoesGlobais.join(gbImvl,",") + " FROM imoveis i WHERE " + gbImvl[0].toLowerCase() + (jcbHeuristica.isSelected() ? " LIKE '%" : " LIKE '") + sBusca + "%' OR " +
            gbImvl[1].toLowerCase() + (jcbHeuristica.isSelected() ? " LIKE '%" : " LIKE '") + sBusca + "%' OR " + gbImvl[2].toLowerCase() + (jcbHeuristica.isSelected() ? " LIKE '%" : " LIKE '") + sBusca +
                    "%' OR " + gbImvl[6].toLowerCase() + (jcbHeuristica.isSelected() ? " LIKE '%" : " LIKE '") + sBusca + "%'";

            TableControl.header(jtbBuscas, new String[][] {{"rgprp", "rgimv", "endereço"},{"80","80","500"}});
            ResultSet pResult = this.conn.AbrirTabela(cSql, ResultSet.CONCUR_READ_ONLY);
            try {
                while (pResult.next()) {
                    String trgprp = String.valueOf(pResult.getInt("i.rgprp"));
                    String trgimv = String.valueOf(pResult.getInt("i.rgimv"));
                    String tend = pResult.getString("i.end").toUpperCase().trim() + ", " + pResult.getString("i.num").toUpperCase().trim() + " " + pResult.getString("i.compl").toUpperCase().trim();
                    String tsit = pResult.getString("i.situacao");
                    
                    if (jInativos.isSelected()) {
                        if (tsit.equalsIgnoreCase("DESATIVADO")) TableControl.add(jtbBuscas, new String[][]{{trgprp, trgimv, tend},{"C","C","L"}},true);
                    } else {
                        if (!tsit.equalsIgnoreCase("DESATIVADO")) TableControl.add(jtbBuscas, new String[][]{{trgprp, trgimv, tend},{"C","C","L"}},true);
                    }
                    
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            DbMain.FecharTabela(pResult);

        } else if (jrbFiadores.isSelected()) {
            cSql = "SELECT " + FuncoesGlobais.join(gbFiad,",") + " FROM fiadores f WHERE Lower(" + gbFiad[0].toLowerCase() + (jcbHeuristica.isSelected() ? ") LIKE '%" : ") LIKE '") + sBusca + "%' OR Lower(" +
            gbFiad[1].toLowerCase() + (jcbHeuristica.isSelected() ? ") LIKE '%" : ") LIKE '") + sBusca + "%' OR Lower(" + gbFiad[2].toLowerCase() + (jcbHeuristica.isSelected() ? ") LIKE '%" : ") LIKE '") + sBusca +
            "%' OR Lower(" + gbFiad[3].toLowerCase() + (jcbHeuristica.isSelected() ? ") LIKE '%" : ") LIKE '") + sBusca + "%'";

            TableControl.header(jtbBuscas, new String[][] {{"contrato", "rgimv", "nome", "cpf/cnpj"},{"80","80","500","150"}});
            ResultSet pResult = this.conn.AbrirTabela(cSql, ResultSet.CONCUR_READ_ONLY);
            try {
                while (pResult.next()) {
                    String tcontrato = String.valueOf(pResult.getInt("f.contrato"));
                    String trgimv = String.valueOf(pResult.getInt("f.rgimv"));
                    String tnome = pResult.getString("f.nomerazao").toUpperCase().trim();
                    String tcpfcnpj = pResult.getString("f.cpfcnpj").toUpperCase().trim();
                    TableControl.add(jtbBuscas, new String[][]{{tcontrato, trgimv, tnome, tcpfcnpj},{"C","C","L","C"}},true);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            DbMain.FecharTabela(pResult);
        } else if (jrbboletas.isSelected()) {        
            //cSql = "SELECT " + FuncoesGlobais.join(gbBole,",") + " FROM recibo r WHERE (r.contrato = l.contrato) AND Trim(r.nnumero) <> '' AND " + 
            //       "Lower(" + gbBole[0].toLowerCase() + (jcbHeuristica.isSelected() ? ") LIKE '%" : ") LIKE '") + sBusca + "%' OR Lower(" +
            //gbBole[1].toLowerCase() + (jcbHeuristica.isSelected() ? ") LIKE '%" : ") LIKE '") + sBusca + "%' ORDER BY r.dtvencimento DESC LIMIT 50;";

            cSql = "SELECT r.nnumero, r.contrato, (SELECT l.nomerazao FROM locatarios l WHERE l.contrato = r.contrato) AS nomerazao, " +
                   "r.dtvencimento, r.tag FROM recibo r WHERE " +
                   "Trim(r.nnumero) <> '' AND " +
                   "Lower(r.nnumero) " + (jcbHeuristica.isSelected() ? " LIKE '%" : " LIKE '") + sBusca + "%' OR " +
                   "Lower(r.contrato) " + (jcbHeuristica.isSelected() ? " LIKE '%" : " LIKE '") + sBusca + "%' " +
                   "ORDER BY r.dtvencimento DESC LIMIT 50;";
            
            TableControl.header(jtbBuscas, new String[][] {{"nnumero", "contrato", "nome", "vencimento","tag"},{"120","70","250","90","80"}});
            ResultSet pResult = this.conn.AbrirTabela(cSql, ResultSet.CONCUR_READ_ONLY);
            try {
                while (pResult.next()) {
                    String tnnumero = pResult.getString("nnumero");
                    String tcontrato = String.valueOf(pResult.getInt("contrato"));
                    String tnome = pResult.getString("nomerazao").toUpperCase().trim();
                    String tvecto = Dates.DateFormata("dd/MM/yyyy", pResult.getDate("dtvencimento"));
                    String tvalor = pResult.getString("tag");
                    TableControl.add(jtbBuscas, new String[][]{{tnnumero, tcontrato, tnome, tvecto, tvalor},{"C","C","L","C","R"}},true);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            DbMain.FecharTabela(pResult);
       }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jInativos;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcbHeuristica;
    private javax.swing.JRadioButton jrbFiadores;
    private javax.swing.JRadioButton jrbImoveis;
    private javax.swing.JRadioButton jrbLoca;
    private javax.swing.JRadioButton jrbProp;
    private javax.swing.JRadioButton jrbboletas;
    private javax.swing.JTable jtbBuscas;
    // End of variables declaration//GEN-END:variables
}
