/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sici.Partida;

import Funcoes.DbMain;
import Funcoes.FuncoesGlobais;
import Funcoes.VariaveisGlobais;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Rectangle;
import java.lang.String;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JCheckBox;
import javax.swing.JLabel;

/**
 *
 * @author supervisor
 */
public class jUserAcesso extends javax.swing.JInternalFrame {
    DbMain conn = VariaveisGlobais.conexao;

    /**
     * Creates new form jUserAcesso
     */
    public jUserAcesso() {
        initComponents();
        
        cbUsuarios.setModel(new javax.swing.DefaultComboBoxModel(ListaUsuarios()));
        MontaAcessos();
        
    }

    private String[] ListaUsuarios() {
        ResultSet rst = conn.AbrirTabela("SELECT f_cod, f_nome FROM cadfun ORDER BY Upper(f_nome);", ResultSet.CONCUR_READ_ONLY);
        String[] lista = {};
        try {
            while (rst.next()) {
                String _cod = rst.getString("f_cod");
                String _nome = rst.getString("f_nome");
                
                lista = FuncoesGlobais.ArrayAdd(lista, _cod + " - " + _nome );
            }
        } catch (SQLException ex) {}
        DbMain.FecharTabela(rst);

        return lista;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbUsuarios = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlAcessos = new javax.swing.JPanel();
        btMostrar = new javax.swing.JButton();
        btGravar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle(".:: Acesso ao Sistema...");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jLabel1.setText("Selecione o usuário:");

        javax.swing.GroupLayout pnlAcessosLayout = new javax.swing.GroupLayout(pnlAcessos);
        pnlAcessos.setLayout(pnlAcessosLayout);
        pnlAcessosLayout.setHorizontalGroup(
            pnlAcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        pnlAcessosLayout.setVerticalGroup(
            pnlAcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnlAcessos);

        btMostrar.setText("Mostrar");
        btMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarActionPerformed(evt);
            }
        });

        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMostrar)
                    .addComponent(btGravar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarActionPerformed
        String _cod = cbUsuarios.getSelectedItem().toString().trim().substring(0, 2);
        String chaves = null;
        try {chaves = conn.LerCamposTabela(new String[] {"atalhos"}, "cadfun", "f_cod = '" + _cod + "'")[0][3];} catch (Exception e) {}
        if (chaves != null) {
            Mostrar(chaves);
        }
        
    }//GEN-LAST:event_btMostrarActionPerformed

    private void Mostrar(String chaves) {
        String _tree = chaves.replaceAll(";", ",");
        String[] _nodes = _tree.split(",");
        
        int i = 0; int maxcpos = pnlAcessos.getComponentCount(); int j = 0;
        String _chaves = "", _chave = "";
        for (i=0; i <= maxcpos - 1; i++) {
            if (pnlAcessos.getComponent(i) instanceof JLabel) {
                // Não faz nada
            } else if (pnlAcessos.getComponent(i) instanceof JCheckBox) {
                _chave = ((JCheckBox) pnlAcessos.getComponent(i)).getName();
                for (int z=0;z<_nodes.length;z++) {
                    int pos = FuncoesGlobais.OcourCount(_nodes[z], ":", 2);
                    String _node = _nodes[z].substring(0, pos);
                    boolean _setar = (_chave.trim().equalsIgnoreCase(_node.trim()));
                    if (_setar) {
                        String[] _acesso = _nodes[z].split(":");
                         ((JCheckBox) pnlAcessos.getComponent(i)).setSelected(_acesso[2].trim().equalsIgnoreCase("1") ? true : false);
                    }        
                }
            }
        }
        
    }
    
    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        String chaves = Chaves();
        String _cod = cbUsuarios.getSelectedItem().toString().trim().substring(0, 2);
        String sql = "UPDATE cadfun SET atalhos = '" + chaves + "' WHERE f_cod = '" + _cod + "';";
        try {conn.ExecutarComando(sql);} catch (Exception e) {}
    }//GEN-LAST:event_btGravarActionPerformed

    private String Chaves () {
        int i = 0; int maxcpos = pnlAcessos.getComponentCount(); int j = 0;
        String _chaves = "", _chave = "";
        for (i=0; i <= maxcpos - 1; i++) {
            if (pnlAcessos.getComponent(i) instanceof JLabel) {
                _chave = (i>0 ? ";" : "") + ((JLabel) pnlAcessos.getComponent(i)).getName() + ":0";
            } else if (pnlAcessos.getComponent(i) instanceof JCheckBox) {
                boolean simnao = ((JCheckBox) pnlAcessos.getComponent(i)).isSelected();
                if (simnao) {
                    _chave = ((JCheckBox) pnlAcessos.getComponent(i)).getName() + ":1";
                } else {
                    _chave = ((JCheckBox) pnlAcessos.getComponent(i)).getName() + ":0";
                }
            }
            _chaves += _chave + ",";
        }
    
        // Acertas (.;)
        _chaves = _chaves.replaceAll(",;", ";");
        
        String[] chaves = _chaves.split(";");
        for (int z=0;z<chaves.length;z++) {
            String[] nodes = chaves[z].split(",");
            boolean root = false;
            for (int w=0;w<nodes.length;w++) { 
                String[] tree = nodes[w].split(":");
                root = root || tree[2].trim().equalsIgnoreCase("1");
            }
            // Faz root = true
            String _node = "";
            if (root) {
               String[] tree = nodes[0].split(":");
               tree[2] = "1";
               
               nodes[0] = tree[0] + ":" + tree[1] + ":" + tree[2];
            } 
            chaves[z] = FuncoesGlobais.join(nodes, ",");
            System.out.println();
        }
        
        return FuncoesGlobais.join(chaves, ";");
    }

    private void MontaAcessos() {
        ResultSet mnu = conn.AbrirTabela("SELECT * FROM menu ORDER BY tipo,cod;", ResultSet.CONCUR_READ_ONLY);
        try {
            int _ypos = 0;
            int _iwidth = 730;
            while (mnu.next()) {
                int _tipo = mnu.getInt(("tipo"));
                int _cod  = mnu.getInt("cod");
                String _nome = mnu.getString("nome").trim().toUpperCase();

                int _xpos = (_cod == 0 ? 0 : 30);
                int _width = (_cod ==0 ? _iwidth : _iwidth - 30);
                int _heigth = 24;
                
                Component item = null;
                if (_cod != 0) {
                    JCheckBox _item = new JCheckBox(_nome);
                    _item.setName(_tipo + ":" + _cod);
                    _item.setBounds(new Rectangle(_xpos, _ypos, _width, _heigth));
                    Color _corBG = new Color(90, 90, 220);
                    Color _corBG2 = pnlAcessos.getBackground();
                    Color _corFG = new Color(254,254,254);
                    Color _corFG2 = new Color(76,76,76);
                    _item.setForeground(_cod == 0 ? _corFG : _corFG2);
                    _item.setBackground(_cod == 0 ? _corBG : _corBG2);
                    _item.setOpaque(true);
                    _item.setBorderPainted(true);
                    //_item.setBorderPaintedFlat(true);
                    _item.setVisible(true);
                    item = _item;
                } else {
                    JLabel _item = new JLabel("   " + _nome);
                    _item.setName(_tipo + ":" + _cod);
                    _item.setBounds(new Rectangle(_xpos, _ypos, _width, _heigth));
                    Color _corBG = new Color(90, 90, 220);
                    Color _corBG2 = pnlAcessos.getBackground();
                    Color _corFG = new Color(254,254,254);
                    Color _corFG2 = new Color(76,76,76);
                    _item.setForeground(_cod == 0 ? _corFG : _corFG2);
                    _item.setBackground(_cod == 0 ? _corBG : _corBG2);
                    _item.setOpaque(true);
                    _item.setVisible(true);
                    _item.setFont(new Font("Ubuntu", 1, 15));
                    item = _item;
                }
                
                pnlAcessos.add(item);
                _ypos += 29;
            }
            pnlAcessos.setPreferredSize(new Dimension(_iwidth, _ypos));
        } catch (Exception e) {e.printStackTrace();}
        DbMain.FecharTabela(mnu);        
    }
    
    private void ShowAcessos(String _cod) {
        String _atalhos = null;
        try { _atalhos = conn.LerCamposTabela(new String[] {"atalhos"}, "cadfun", "f_cod = '" + _cod + "'")[0][3];} catch (Exception e) {}
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btMostrar;
    private javax.swing.JComboBox cbUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlAcessos;
    // End of variables declaration//GEN-END:variables
}
