/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Exclusao;

import Funcoes.DbMain;
import Funcoes.TableControl;
import Funcoes.VariaveisGlobais;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author supervisor
 */
public class RetornaExcluido extends javax.swing.JInternalFrame {
    private DbMain conn;
    TableRowSorter<TableModel> sorterp; TableRowSorter<TableModel> sorterl;

    /**
     * Creates new form RetornaExcluido
     */
    public RetornaExcluido() {
        initComponents();
        
        conn = new DbMain(VariaveisGlobais.unidade,"root",(VariaveisGlobais.dbsenha ? "7kf51b" : ""),"jgeral_excluidos");
        
        // Seta Cabecarios
        TableControl.header(jtblProp, new String[][] {{"rgprp","nome",},{"20","500"}});
        TableControl.header(jtblLoca, new String[][] {{"rgprp","rgimv","contrato","nome",},{"0","0","20","500"}});

        String Sql = "SELECT rgprp, nome FROM proprietarios ORDER BY Upper(nome);";
        ResultSet rs = conn.AbrirTabela(Sql, ResultSet.CONCUR_READ_ONLY);
        try {
            while (rs.next()) {
                TableControl.add(jtblProp, new String[][]{{rs.getString("rgprp"), rs.getString("nome").toUpperCase()},{"C","L"}}, true);
            }
        } catch (Exception e) {}
        try { DbMain.FecharTabela(rs); } catch (Exception e) {}
        sorterp = new TableRowSorter<TableModel>(jtblProp.getModel());
        jtblProp.setRowSorter(sorterp);

        Sql = "SELECT DISTINCT rgprp, rgimv, contrato, nomerazao FROM jgeral_excluidos.locatarios WHERE rgprp not in (SELECT DISTINCT rgprp FROM jgeral_excluidos.proprietarios) ORDER BY Upper(nomerazao);";
        rs = conn.AbrirTabela(Sql, ResultSet.CONCUR_READ_ONLY);
        try {
            while (rs.next()) {
                TableControl.add(jtblLoca, new String[][]{{rs.getString("rgprp"), rs.getString("rgimv"), rs.getString("contrato"), rs.getString("nomerazao").toUpperCase()},{"C","C","C","L"}}, true);
            }
        } catch (Exception e) {}
        try { DbMain.FecharTabela(rs); } catch (Exception e) {}
        sorterl = new TableRowSorter<TableModel>(jtblLoca.getModel());
        jtblLoca.setRowSorter(sorterl);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProp = new javax.swing.JTable();
        jtfBuscarProp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblLoca = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtfBuscarLoca = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle(".:: Retorna Excluidos do Sistema Sici ::.");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jtblProp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "rgprp", "nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblProp.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtblProp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtblPropKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtblProp);

        jtfBuscarProp.setBackground(new java.awt.Color(254, 254, 254));
        jtfBuscarProp.setBorder(null);
        jtfBuscarProp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscarPropKeyReleased(evt);
            }
        });

        jLabel2.setText("Buscar:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBuscarProp)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfBuscarProp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        jTabbedPane1.addTab("Proprietários", jPanel1);

        jtblLoca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "rgprp", "rgimv", "contrato", "nomerazao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblLoca.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtblLoca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtblLocaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtblLoca);

        jLabel1.setText("Buscar:");

        jtfBuscarLoca.setBackground(new java.awt.Color(254, 254, 254));
        jtfBuscarLoca.setBorder(null);
        jtfBuscarLoca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscarLocaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBuscarLoca)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtfBuscarLoca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Locatários", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfBuscarPropKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarPropKeyReleased
        if ("".equals(jtfBuscarProp.getText().trim())) {
            sorterp.setRowFilter(null);
        } else {
            sorterp.setRowFilter(RowFilter.regexFilter(jtfBuscarProp.getText().trim()));
        }
    }//GEN-LAST:event_jtfBuscarPropKeyReleased

    private void jtfBuscarLocaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarLocaKeyReleased
        if ("".equals(jtfBuscarLoca.getText().trim())) {
            sorterl.setRowFilter(null);
        } else {
            sorterl.setRowFilter(RowFilter.regexFilter(jtfBuscarLoca.getText().trim()));
        }
    }//GEN-LAST:event_jtfBuscarLocaKeyReleased

    private void jtblPropKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtblPropKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            Object[] options = { "Sim", "Não" };
            int n = JOptionPane.showOptionDialog(null,
                "Deseja retornar este Proprietário ? ",
                "Atenção", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if (n == JOptionPane.NO_OPTION) return;
        }
        
        if (jtblProp.getSelectedRow() == -1) return;
        
        int selRow = jtblProp.convertRowIndexToModel(jtblProp.getSelectedRow());
        String rgprp = (String) jtblProp.getModel().getValueAt(selRow, 0);
        
        String[] cmds = new String[] {
            "INSERT INTO " + VariaveisGlobais.dbnome + ".parametros (`VARIAVEL`,`CONTEUDO`,`TIPO`) SELECT `VARIAVEL`,`CONTEUDO`,`TIPO` FROM jgeral_excluidos.parametros WHERE variavel LIKE 'PROP" + rgprp + "';",
            "DELETE FROM jgeral_excluidos.parametros WHERE variavel LIKE 'PROP" + rgprp + "';",
            
            "INSERT INTO " + VariaveisGlobais.dbnome + ".multa (`PA_MULTA`,`PA_COR`,`PA_JUR`,`MULTA_RES`,`MULTA_COM`,`COR_TIPO`,`COR_CORR`," +
            "`PER_JUR`,`DIA_MUL`,`DIA_COR`,`DIA_JUR`,`TE_PER`,`TE_VRM`,`TE_NOME`,`TXEXP`,`TBRLIQ`,`REGRA`,`RGPRP`,`RGIMV`,`COR_LIM_A`,`COMISSAO`) " + 
            "SELECT `PA_MULTA`,`PA_COR`,`PA_JUR`,`MULTA_RES`,`MULTA_COM`,`COR_TIPO`,`COR_CORR`," +
            "`PER_JUR`,`DIA_MUL`,`DIA_COR`,`DIA_JUR`,`TE_PER`,`TE_VRM`,`TE_NOME`,`TXEXP`,`TBRLIQ`,`REGRA`,`RGPRP`,`RGIMV`,`COR_LIM_A`,`COMISSAO` FROM jgeral_excluidos.multa WHERE rgprp = '" + rgprp + "';",
            "DELETE FROM jgeral_excluidos.multa WHERE rgprp = '" + rgprp + "';",
            
            "INSERT INTO " + VariaveisGlobais.dbnome + ".proprietarios (`rgprp`,`nome`,`tipoprop`,`end`,`num`,`compl`,`bairro`,`cidade`,`estado`," +
            "`cep`,`tel`,`profissao`,`representante`,`repdtnasc`,`naciona`,`ecivil`,`dtnasc`,`rginsc`,`cpfcnpj`,`conjugue`,`conjdtnasc`,`banco`," +
            "`agencia`,`conta`,`favorecido`,`email`,`dtcadastro`,`status`,`dtsaida`,`msgboleta`,`msgrecibo`,`obscaixa`,`correio`,`cor_end`," +
            "`cor_num`,`cor_compl`,`cor_bairro`,`cor_cidade`,`cor_estado`,`cor_cep`,`dtultpagto`,`vrultpagto`,`saldoant`,`sexo`) " + 
            "SELECT `rgprp`,`nome`,`tipoprop`,`end`,`num`,`compl`,`bairro`,`cidade`,`estado`," +
            "`cep`,`tel`,`profissao`,`representante`,`repdtnasc`,`naciona`,`ecivil`,`dtnasc`,`rginsc`,`cpfcnpj`,`conjugue`,`conjdtnasc`,`banco`," +
            "`agencia`,`conta`,`favorecido`,`email`,`dtcadastro`,`status`,`dtsaida`,`msgboleta`,`msgrecibo`,`obscaixa`,`correio`,`cor_end`," +
            "`cor_num`,`cor_compl`,`cor_bairro`,`cor_cidade`,`cor_estado`,`cor_cep`,`dtultpagto`,`vrultpagto`,`saldoant`,`sexo` FROM jgeral_excluidos.proprietarios WHERE rgprp = '" + rgprp + "';",
            "DELETE FROM jgeral_excluidos.proprietarios WHERE rgprp = '" + rgprp + "';",
            
            "INSERT INTO " + VariaveisGlobais.dbnome + ".imoveis (`rgprp`,`rgimv`,`tpimovel`,`tpurbrural`,`end`,`num`,`compl`,`bairro`," +
            "`cidade`,`codcid`,`estado`,`cep`,`especifica`,`situacao`,`menssagem`,`obs`,`reter`,`matriculas`,`fotos`) " + 
            "SELECT `rgprp`,`rgimv`,`tpimovel`,`tpurbrural`,`end`,`num`,`compl`,`bairro`,`cidade`,`codcid`,`estado`,`cep`,`especifica`," + 
            "`situacao`,`menssagem`,`obs`,`reter`,`matriculas`,`fotos` FROM jgeral_excluidos.imoveis where rgprp = '" + rgprp + "';",
            "DELETE FROM jgeral_excluidos.imoveis WHERE rgprp = '" + rgprp + "';",
            
            "INSERT INTO " + VariaveisGlobais.dbnome + ".locatarios (`contrato`,`rgimv`,`rgprp`,`tpimovel`,`tploca`,`cpfcnpj`,`rginsc`," +
            "`dtnasc`,`nomerazao`,`fantasia`,`end`,`num`,`compl`,`bairro`,`cidade`,`estado`,`cep`,`tel`,`ramal`,`celular`,`naciona`," +
            "`ecivil`,`pai`,`mae`,`empresa`,`cargo`,`salario`,`dtadmis`,`email`,`conjugue`,`cjdtnasc`,`cjempresa`,`cjtel`,`cjramal`," +
            "`cjsalario`,`aviso`,`boleta`,`msgboleta`,`cor_nome`,`cor_end`,`cor_num`,`cor_compl`,`cor_bairro`,`cor_cidade`,`cor_estado`," +
            "`cor_cep`,`sociodtnasc1`,`socionac1`,`socioecivil1`,`sociocpf1`,`sociorg1`,`sociopai1`,`sociomae1`,`sociosalario1`," +
            "`sociocargo1`,`socionome1`,`sociodtnasc2`,`socionac2`,`socioecivil2`,`sociocpf2`,`sociorg2`,`sociopai2`,`sociomae2`," +
            "`sociosalario2`,`sociocargo2`,`socionome2`,`sociodtnasc3`,`socionac3`,`socioecivil3`,`sociocpf3`,`sociorg3`,`sociopai3`," +
            "`sociomae3`,`sociosalario3`,`sociocargo3`,`socionome3`,`sociodtnasc4`,`socionac4`,`socioecivil4`,`sociocpf4`,`sociorg4`," +
            "`sociopai4`,`sociomae4`,`sociosalario4`,`sociocargo4`,`socionome4`,`fiador1dtnasc`,`fiador1ecivil`,`fiador1nac`,`fiador1tel`," +
            "`fiador1pai`,`fiador1mae`,`fiador1emp`,`fiador1empdtadmis`,`fiador1end`,`fiador1uf`,`fiador1compl`,`fiador1bairro`,`fiador1cidade`," +
            "`fiador1num`,`fiador1cep`,`fiador1telemp`,`fiador1empramal`,`fiador1empcargo`,`fiador1empsalario`,`fiador1conj`,`fiador1conjemp`," +
            "`fiador1conjdtnasc`,`fiador1conjemptel`,`fiador1conjempramal`,`fiador1conjempsalario`,`fiador1empcelular`,`fiador1email`," +
            "`fiador1nome`,`fiador1cpf`,`fiador1rg`,`fiador2dtnasc`,`fiador2ecivil`,`fiador2nac`,`fiador2tel`,`fiador2pai`,`fiador2mae`," +
            "`fiador2emp`,`fiador2empdtadmis`,`fiador2end`,`fiador2uf`,`fiador2compl`,`fiador2bairro`,`fiador2cidade`,`fiador2num`," +
            "`fiador2cep`,`fiador2telemp`,`fiador2empramal`,`fiador2empcargo`,`fiador2empsalario`,`fiador2conj`,`fiador2conjemp`," +
            "`fiador2conjdtnasc`,`fiador2conjemptel`,`fiador2conjempramal`,`fiador2conjempsalario`,`fiador2empcelular`,`fiador2email`," +
            "`fiador2nome`,`fiador2cpf`,`fiador2rg`,`fi_cornome`,`fi_cornum`,`fi_corcompl`,`fi_corbai`,`fi_corcid`,`fi_coruf`,`fi_corcep`," +
            "`fi_corend`,`historico`,`cjrg`,`cjcpf`,`sexo`,`conjsexo`,`envio`,`bcobol`) " + 
            "SELECT `contrato`,`rgimv`,`rgprp`,`tpimovel`,`tploca`,`cpfcnpj`,`rginsc`," +
            "`dtnasc`,`nomerazao`,`fantasia`,`end`,`num`,`compl`,`bairro`,`cidade`,`estado`,`cep`,`tel`,`ramal`,`celular`,`naciona`," +
            "`ecivil`,`pai`,`mae`,`empresa`,`cargo`,`salario`,`dtadmis`,`email`,`conjugue`,`cjdtnasc`,`cjempresa`,`cjtel`,`cjramal`," +
            "`cjsalario`,`aviso`,`boleta`,`msgboleta`,`cor_nome`,`cor_end`,`cor_num`,`cor_compl`,`cor_bairro`,`cor_cidade`,`cor_estado`," +
            "`cor_cep`,`sociodtnasc1`,`socionac1`,`socioecivil1`,`sociocpf1`,`sociorg1`,`sociopai1`,`sociomae1`,`sociosalario1`," +
            "`sociocargo1`,`socionome1`,`sociodtnasc2`,`socionac2`,`socioecivil2`,`sociocpf2`,`sociorg2`,`sociopai2`,`sociomae2`," +
            "`sociosalario2`,`sociocargo2`,`socionome2`,`sociodtnasc3`,`socionac3`,`socioecivil3`,`sociocpf3`,`sociorg3`,`sociopai3`," +
            "`sociomae3`,`sociosalario3`,`sociocargo3`,`socionome3`,`sociodtnasc4`,`socionac4`,`socioecivil4`,`sociocpf4`,`sociorg4`," +
            "`sociopai4`,`sociomae4`,`sociosalario4`,`sociocargo4`,`socionome4`,`fiador1dtnasc`,`fiador1ecivil`,`fiador1nac`,`fiador1tel`," +
            "`fiador1pai`,`fiador1mae`,`fiador1emp`,`fiador1empdtadmis`,`fiador1end`,`fiador1uf`,`fiador1compl`,`fiador1bairro`,`fiador1cidade`," +
            "`fiador1num`,`fiador1cep`,`fiador1telemp`,`fiador1empramal`,`fiador1empcargo`,`fiador1empsalario`,`fiador1conj`,`fiador1conjemp`," +
            "`fiador1conjdtnasc`,`fiador1conjemptel`,`fiador1conjempramal`,`fiador1conjempsalario`,`fiador1empcelular`,`fiador1email`," +
            "`fiador1nome`,`fiador1cpf`,`fiador1rg`,`fiador2dtnasc`,`fiador2ecivil`,`fiador2nac`,`fiador2tel`,`fiador2pai`,`fiador2mae`," +
            "`fiador2emp`,`fiador2empdtadmis`,`fiador2end`,`fiador2uf`,`fiador2compl`,`fiador2bairro`,`fiador2cidade`,`fiador2num`," +
            "`fiador2cep`,`fiador2telemp`,`fiador2empramal`,`fiador2empcargo`,`fiador2empsalario`,`fiador2conj`,`fiador2conjemp`," +
            "`fiador2conjdtnasc`,`fiador2conjemptel`,`fiador2conjempramal`,`fiador2conjempsalario`,`fiador2empcelular`,`fiador2email`," +
            "`fiador2nome`,`fiador2cpf`,`fiador2rg`,`fi_cornome`,`fi_cornum`,`fi_corcompl`,`fi_corbai`,`fi_corcid`,`fi_coruf`,`fi_corcep`," +
            "`fi_corend`,`historico`,`cjrg`,`cjcpf`,`sexo`,`conjsexo`,`envio`,`bcobol` FROM jgeral_excluidos.locatarios where rgprp = '" + rgprp + "';",
            "DELETE FROM jgeral_excluidos.locatarios WHERE rgprp = '" + rgprp + "';",
            
            "INSERT INTO " + VariaveisGlobais.dbnome + ".carteira (`RGPRP`,`RGIMV`,`CONTRATO`,`CAMPO`,`DTINICIO`,`DTTERMINO`,`DTULTRECEBIMENTO`," +
            "`DTVENCIMENTO`,`VRSEGURO`,`PCSEGURO`,`DTSEGURO`,`DTADITO`) SELECT `RGPRP`,`RGIMV`,`CONTRATO`,`CAMPO`,`DTINICIO`,`DTTERMINO`,`DTULTRECEBIMENTO`," +
            "`DTVENCIMENTO`,`VRSEGURO`,`PCSEGURO`,`DTSEGURO`,`DTADITO` FROM jgeral_excluidos.carteira where rgprp = '" + rgprp + "';",
            "DELETE FROM jgeral_excluidos.carteira WHERE rgprp = '" + rgprp + "';",
            
            "INSERT INTO " + VariaveisGlobais.dbnome + ".fiadores (`contrato`,`rgimv`,`rgprp`,`tploca`,`cpfcnpj`,`rginsc`,`dtnasc`,`nomerazao`," +
            "`fantasia`,`end`,`num`,`compl`,`bairro`,`cidade`,`estado`,`cep`,`tel`,`ramal`,`celular`,`naciona`,`ecivil`,`pai`,`mae`,`empresa`," +
            "`cargo`,`salario`,`dtadmis`,`email`,`conjugue`,`cjdtnasc`,`cjempresa`,`cjtel`,`cjramal`,`cjsalario`,`cjrg`,`cjcpf`,`aviso`," +
            "`boleta`,`msgboleta`,`cor_nome`,`cor_end`,`cor_num`,`cor_compl`,`cor_bairro`,`cor_cidade`,`cor_estado`,`cor_cep`,`sociodtnasc1`," +
            "`socionac1`,`socioecivil1`,`sociocpf1`,`sociorg1`,`sociopai1`,`sociomae1`,`sociosalario1`,`sociocargo1`,`socionome1`,`sociodtnasc2`," +
            "`socionac2`,`socioecivil2`,`sociocpf2`,`sociorg2`,`sociopai2`,`sociomae2`,`sociosalario2`,`sociocargo2`,`socionome2`,`sociodtnasc3`," +
            "`socionac3`,`socioecivil3`,`sociocpf3`,`sociorg3`,`sociopai3`,`sociomae3`,`sociosalario3`,`sociocargo3`,`socionome3`,`sociodtnasc4`," +
            "`socionac4`,`socioecivil4`,`sociocpf4`,`sociorg4`,`sociopai4`,`sociomae4`,`sociosalario4`,`sociocargo4`,`socionome4`) " + 
            "SELECT `contrato`,`rgimv`,`rgprp`,`tploca`,`cpfcnpj`,`rginsc`,`dtnasc`,`nomerazao`," +
            "`fantasia`,`end`,`num`,`compl`,`bairro`,`cidade`,`estado`,`cep`,`tel`,`ramal`,`celular`,`naciona`,`ecivil`,`pai`,`mae`,`empresa`," +
            "`cargo`,`salario`,`dtadmis`,`email`,`conjugue`,`cjdtnasc`,`cjempresa`,`cjtel`,`cjramal`,`cjsalario`,`cjrg`,`cjcpf`,`aviso`," +
            "`boleta`,`msgboleta`,`cor_nome`,`cor_end`,`cor_num`,`cor_compl`,`cor_bairro`,`cor_cidade`,`cor_estado`,`cor_cep`,`sociodtnasc1`," +
            "`socionac1`,`socioecivil1`,`sociocpf1`,`sociorg1`,`sociopai1`,`sociomae1`,`sociosalario1`,`sociocargo1`,`socionome1`,`sociodtnasc2`," +
            "`socionac2`,`socioecivil2`,`sociocpf2`,`sociorg2`,`sociopai2`,`sociomae2`,`sociosalario2`,`sociocargo2`,`socionome2`,`sociodtnasc3`," +
            "`socionac3`,`socioecivil3`,`sociocpf3`,`sociorg3`,`sociopai3`,`sociomae3`,`sociosalario3`,`sociocargo3`,`socionome3`,`sociodtnasc4`," +
            "`socionac4`,`socioecivil4`,`sociocpf4`,`sociorg4`,`sociopai4`,`sociomae4`,`sociosalario4`,`sociocargo4`,`socionome4` FROM jgeral_excluidos.fiadores where rgprp = '" + rgprp + "';",
            "DELETE FROM jgeral_excluidos.fiadores WHERE rgprp = '" + rgprp + "';",
            
            "INSERT INTO " + VariaveisGlobais.dbnome + ".auxiliar (`CONTA`,`RGPRP`,`RGIMV`,`CONTRATO`,`CAMPO`,`DTVENCIMENTO`,`DTRECEBIMENTO`," +
            "`RC_AUT`) SELECT `CONTA`,`RGPRP`,`RGIMV`,`CONTRATO`,`CAMPO`,`DTVENCIMENTO`,`DTRECEBIMENTO`,`RC_AUT` FROM jgeral_excluidos.auxiliar where `RGPRP` = '" + rgprp + "';",
            "DELETE FROM jgeral_excluidos.auxiliar WHERE rgprp = '" + rgprp + "';",
            
            "INSERT INTO " + VariaveisGlobais.dbnome + ".avisos (`RID`,`registro`,`campo`,`tag`,`autenticacao`,`et_aut`) SELECT `RID`,`registro`,`campo`,`tag`,`autenticacao`,`et_aut` FROM jgeral_excluidos.avisos where `registro` = '" + rgprp + "';",
            "DELETE FROM jgeral_excluidos.avisos WHERE `registro` = '" + rgprp + "';",
            
            "INSERT INTO " + VariaveisGlobais.dbnome + ".caixa (`CX_AUT`,`CX_DATA`,`CX_HORA`,`CX_LOGADO`,`CX_CONTRATO`,`CX_RGPRP`," +
            "`CX_RGIMV`,`CX_OPER`,`CX_VRDN`,`CX_VRCH`,`CX_CHREL`,`CX_TIPOPG`,`CX_DOC`,`CX_NDOCS`) " + 
            "SELECT `CX_AUT`,`CX_DATA`,`CX_HORA`,`CX_LOGADO`,`CX_CONTRATO`,`CX_RGPRP`," +
            "`CX_RGIMV`,`CX_OPER`,`CX_VRDN`,`CX_VRCH`,`CX_CHREL`,`CX_TIPOPG`,`CX_DOC`,`CX_NDOCS` FROM jgeral_excluidos.caixa WHERE `CX_RGPRP` = '" + rgprp + "';",
            "DELETE FROM jgeral_excluidos.caixa WHERE cx_rgprp = '" + rgprp + "';",
            
            "INSERT INTO " + VariaveisGlobais.dbnome + ".caixabck (`CX_AUT`,`CX_DATA`,`CX_HORA`,`CX_LOGADO`,`CX_CONTRATO`,`CX_RGPRP`," +
            "`CX_RGIMV`,`CX_OPER`,`CX_VRDN`,`CX_VRCH`,`CX_CHREL`,`CX_TIPOPG`,`CX_DOC`,`CX_NDOCS`) " + 
            "SELECT `CX_AUT`,`CX_DATA`,`CX_HORA`,`CX_LOGADO`,`CX_CONTRATO`,`CX_RGPRP`," +
            "`CX_RGIMV`,`CX_OPER`,`CX_VRDN`,`CX_VRCH`,`CX_CHREL`,`CX_TIPOPG`,`CX_DOC`,`CX_NDOCS` FROM jgeral_excluidos.caixabck where cx_rgprp = '" + rgprp + "';",
            "DELETE FROM jgeral_excluidos.caixabck WHERE cx_rgprp = '" + rgprp + "';",
            
            "INSERT INTO " + VariaveisGlobais.dbnome + ".descontos (`rgprp`,`rgimv`,`contrato`,`descricao`,`valor`,`referencia`,`sigla`) " + 
            "SELECT `rgprp`,`rgimv`,`contrato`,`descricao`,`valor`,`referencia`,`sigla` FROM jgeral_excluidos.descontos where rgprp = '" + rgprp + "';",
            "DELETE FROM jgeral_excluidos.descontos WHERE rgprp = '" + rgprp + "';",

            "INSERT INTO " + VariaveisGlobais.dbnome + ".diferenca (`rgprp`,`rgimv`,`contrato`,`descricao`,`valor`,`referencia`,`sigla`) " + 
            "SELECT `rgprp`,`rgimv`,`contrato`,`descricao`,`valor`,`referencia`,`sigla` FROM jgeral_excluidos.diferenca where rgprp = '" + rgprp + "';",
            "DELETE FROM jgeral_excluidos.diferenca WHERE rgprp = '" + rgprp + "';",

            "INSERT INTO " + VariaveisGlobais.dbnome + ".divisao (`rgprp`,`rgimv`,`benefs`,`divtudo`) SELECT `rgprp`,`rgimv`,`benefs`,`divtudo` FROM jgeral_excluidos.divisao where rgprp = '" + rgprp + "';",
            "DELETE FROM jgeral_excluidos.divisao WHERE rgprp = '" + rgprp + "';",

            "INSERT INTO " + VariaveisGlobais.dbnome + ".extrato (`RGPRP`,`RGIMV`,`CONTRATO`,`CAMPO`,`DTVENCIMENTO`,`DTRECEBIMENTO`,`TAG`,`RC_AUT`,`ET_AUT`,`PR_SDANT`) " + 
            "SELECT `RGPRP`,`RGIMV`,`CONTRATO`,`CAMPO`,`DTVENCIMENTO`,`DTRECEBIMENTO`,`TAG`,`RC_AUT`,`ET_AUT`,`PR_SDANT` FROM jgeral_excluidos.extrato where rgprp = '" + rgprp + "';",
            "DELETE FROM jgeral_excluidos.extrato WHERE rgprp = '" + rgprp + "';",

            "INSERT INTO " + VariaveisGlobais.dbnome + ".recibo (`RGPRP`,`RGIMV`,`CONTRATO`,`CAMPO`,`DTVENCIMENTO`,`TAG`,`AUTENTICACAO`,`NNUMERO`) " + 
            "SELECT `RGPRP`,`RGIMV`,`CONTRATO`,`CAMPO`,`DTVENCIMENTO`,`TAG`,`AUTENTICACAO`,`NNUMERO` FROM jgeral_excluidos.recibo where rgprp = '" + rgprp + "';",
            "DELETE FROM jgeral_excluidos.recibo WHERE rgprp = '" + rgprp + "';",

            "INSERT INTO " + VariaveisGlobais.dbnome + ".retencao (`RGPRP`,`RGIMV`,`CONTRATO`,`CAMPO`,`VENCIMENTO`,`MARCA`,`TAG`,`GAT`," +
            "`RC_AUT`,`RT_AUT`) SELECT `RGPRP`,`RGIMV`,`CONTRATO`,`CAMPO`,`VENCIMENTO`,`MARCA`,`TAG`,`GAT`," +
            "`RC_AUT`,`RT_AUT` FROM jgeral_excluidos.retencao where rgprp = '" + rgprp + "';",
            "DELETE FROM jgeral_excluidos.retencao WHERE rgprp = '" + rgprp + "';",

            "INSERT INTO " + VariaveisGlobais.dbnome + ".seguros (`rgprp`,`rgimv`,`contrato`,`valor`,`referencia`,`sigla`) " + 
            "SELECT `rgprp`,`rgimv`,`contrato`,`valor`,`referencia`,`sigla` FROM jgeral_excluidos.seguros where rgprp = '" + rgprp + "';",
            "DELETE FROM jgeral_excluidos.seguros WHERE rgprp = '" + rgprp + "';"
            
            //"INSERT INTO " + VariaveisGlobais.dbnome + ".locabloq (`contrato`,`nome`,`historico`,`status`,`data`) " + 
            //"SELECT `contrato`,`nome`,`historico`,`status`,`data` FROM jgeral_excluidos.locabloq where rgprp = '" + rgprp + "';",
            //"DELETE FROM jgeral_excluidos.locabloq WHERE rgprp = '" + rgprp + "';"
        };
        
        try {
            for (String cmd : cmds) {
                //System.out.println(cmd);
                conn.ExecutarComando(cmd);
            }
            TableControl.del(jtblProp, selRow);
        } catch (Exception e) {e.printStackTrace();}
        
        try {
            conn.Auditor("RETORNO: PROPRIETARIO", rgprp);
        } catch (Exception e) {}

        JOptionPane.showMessageDialog(null, "Proprietário retornado!!!");
        
    }//GEN-LAST:event_jtblPropKeyReleased

    private void jtblLocaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtblLocaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            Object[] options = { "Sim", "Não" };
            int n = JOptionPane.showOptionDialog(null,
                "Deseja retornar este Proprietário ? ",
                "Atenção", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if (n == JOptionPane.NO_OPTION) return;
        }
        
        if (jtblLoca.getSelectedRow() == -1) return;
        
        int selRow = jtblLoca.convertRowIndexToModel(jtblLoca.getSelectedRow());
        String rgprp = (String) jtblLoca.getModel().getValueAt(selRow, 0);
        String rgimv = (String) jtblLoca.getModel().getValueAt(selRow, 1);
        String contrato = (String) jtblLoca.getModel().getValueAt(selRow, 2);
        
        String[] cmds = new String[] {
            "INSERT INTO " + VariaveisGlobais.dbnome + ".multa SELECT * FROM jgeral_excluidos.multa WHERE contrato = '" + contrato + "';",
            "DELETE FROM jgeral_excluidos.multa WHERE contrato = '" + contrato + "';",
            
            "INSERT INTO " + VariaveisGlobais.dbnome + ".locatarios SELECT * FROM jgeral_excluidos.locatarios where contrato = '" + contrato + "';",
            "DELETE FROM jgeral_excluidos.locatarios WHERE contrato = '" + contrato + "';",
            
            "INSERT INTO " + VariaveisGlobais.dbnome + ".carteira SELECT * FROM jgeral_excluidos.carteira where contrato = '" + contrato + "';",
            "DELETE FROM jgeral_excluidos.carteira WHERE contrato = '" + contrato + "';",
            
            "INSERT INTO " + VariaveisGlobais.dbnome + ".fiadores SELECT * FROM jgeral_excluidos.fiadores where contrato = '" + contrato + "';",
            "DELETE FROM jgeral_excluidos.fiadores WHERE contrato = '" + contrato + "';",
            
            "INSERT INTO " + VariaveisGlobais.dbnome + ".auxiliar SELECT * FROM jgeral_excluidos.auxiliar where contrato = '" + contrato + "';",
            "DELETE FROM jgeral_excluidos.auxiliar WHERE contrato = '" + contrato + "';",
            
            "INSERT INTO " + VariaveisGlobais.dbnome + ".avisos SELECT * FROM jgeral_excluidos.avisos where registro = '" + contrato + "';",
            "DELETE FROM jgeral_excluidos.fiadores WHERE registro = '" + contrato + "';",
            
            "INSERT INTO " + VariaveisGlobais.dbnome + ".caixabck SELECT * FROM jgeral_excluidos.caixabck where cx_contrato = '" + contrato + "';",
            "DELETE FROM jgeral_excluidos.caixabck WHERE cx_contrato = '" + contrato + "';",
            
            "INSERT INTO " + VariaveisGlobais.dbnome + ".descontos SELECT * FROM jgeral_excluidos.descontos where contrato = '" + contrato + "';",
            "DELETE FROM jgeral_excluidos.descontos WHERE contrato = '" + contrato + "';",

            "INSERT INTO " + VariaveisGlobais.dbnome + ".diferenca SELECT * FROM jgeral_excluidos.diferenca where contrato = '" + contrato + "';",
            "DELETE FROM jgeral_excluidos.diferenca WHERE contrato = '" + contrato + "';",

            "INSERT INTO " + VariaveisGlobais.dbnome + ".extrato SELECT * FROM jgeral_excluidos.extrato where contrato = '" + contrato + "';",
            "DELETE FROM jgeral_excluidos.extrato WHERE contrato = '" + contrato + "';",

            "INSERT INTO " + VariaveisGlobais.dbnome + ".recibo SELECT * FROM jgeral_excluidos.recibo where contrato = '" + contrato + "';",
            "DELETE FROM jgeral_excluidos.recibo WHERE contrato = '" + contrato + "';",

            "INSERT INTO " + VariaveisGlobais.dbnome + ".retencao SELECT * FROM jgeral_excluidos.retencao where contrato = '" + contrato + "';",
            "DELETE FROM jgeral_excluidos.retencao WHERE contrato = '" + contrato + "';",

            "INSERT INTO " + VariaveisGlobais.dbnome + ".seguros SELECT * FROM jgeral_excluidos.seguros where contrato = '" + contrato + "';",
            "DELETE FROM jgeral_excluidos.seguros WHERE contrato = '" + contrato + "';",
            
            "UPDATE " + VariaveisGlobais.dbnome + ".imoveis SET situacao = 'ocupado' WHERE rgimv = '" + rgimv + "';"
        };
        
        try {
            for (String cmd : cmds) {
                System.out.println(cmd);
                conn.ExecutarComando(cmd);
            }
            TableControl.del(jtblLoca, selRow);
        } catch (Exception e) {e.printStackTrace();}
        try {
            conn.Auditor("RETORNO: LOCATARIO", contrato);
        } catch (Exception e) {}

        JOptionPane.showMessageDialog(null, "Locatário retornado!!!");

    }//GEN-LAST:event_jtblLocaKeyReleased

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        try { conn.FecharConexao(); } catch (Exception e) {}
    }//GEN-LAST:event_formInternalFrameClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtblLoca;
    private javax.swing.JTable jtblProp;
    private javax.swing.JTextField jtfBuscarLoca;
    private javax.swing.JTextField jtfBuscarProp;
    // End of variables declaration//GEN-END:variables
}
