/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jSuperExtorno.java
 *
 * Created on 16/01/2012, 12:31:42
 */
package Movimento;
import Funcoes.DbMain;
import Funcoes.FuncoesGlobais;
import Funcoes.VariaveisGlobais;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author supervisor
 */
public class jSuperExtorno extends javax.swing.JInternalFrame {
    DbMain conn = VariaveisGlobais.conexao;

    /** Creates new form jSuperExtorno */
    public jSuperExtorno() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtExtornar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jAutenticacao = new javax.swing.JTextField();
        jbtSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListaExtorno = new javax.swing.JList();

        setClosable(true);
        setIconifiable(true);
        setTitle(".:: Super EXTORNO");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        jbtExtornar.setText("Extornar");
        jbtExtornar.setEnabled(false);
        jbtExtornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExtornarActionPerformed(evt);
            }
        });

        jLabel1.setText("Autenticação:");

        jAutenticacao.setForeground(new java.awt.Color(204, 0, 51));
        jAutenticacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jAutenticacao.setText("000000");
        jAutenticacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jAutenticacaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jAutenticacaoFocusLost(evt);
            }
        });

        jbtSair.setText("Sair");
        jbtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSairActionPerformed(evt);
            }
        });

        jListaExtorno.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListaExtorno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jAutenticacao, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtExtornar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAutenticacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtExtornar)
                    .addComponent(jbtSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtExtornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExtornarActionPerformed
        String sql = ""; String[] strings = {};
        try {
            sql = FuncoesGlobais.Subst("UPDATE RECIBO SET tag = '', autenticacao = 0 WHERE autenticacao = '&1.'", new String[] {jAutenticacao.getText()});
            conn.ExecutarComando(sql);            
            strings = FuncoesGlobais.ArrayAdd(strings, "Recibos Extornados!!!");
        } catch (Exception e) {}
        
        try {
            sql = FuncoesGlobais.Subst("DELETE FROM avisos WHERE autenticacao = '&1.'", new String[] {jAutenticacao.getText()});
            conn.ExecutarComando(sql);            
            strings = FuncoesGlobais.ArrayAdd(strings, "Avisos Extornados!!!");
        } catch (Exception e) {}
        
        try {
            sql = FuncoesGlobais.Subst("DELETE FROM Cheques WHERE ch_autenticacao = '&1.'", new String[] {jAutenticacao.getText()});
            conn.ExecutarComando(sql);
            strings = FuncoesGlobais.ArrayAdd(strings, "Cheques Extornados!!!");
        } catch (Exception e) {}
        
        try {
            sql = FuncoesGlobais.Subst("DELETE FROM razao WHERE av_aut = '&1.'", new String[] {jAutenticacao.getText()});
            conn.ExecutarComando(sql);
            strings = FuncoesGlobais.ArrayAdd(strings, "Razao Extornados!!!");
        } catch (Exception e) {}
        
        try {
            sql = FuncoesGlobais.Subst("DELETE FROM retencao WHERE rc_aut = '&1.'", new String[] {jAutenticacao.getText()});
            conn.ExecutarComando(sql);
            strings = FuncoesGlobais.ArrayAdd(strings, "Retenções Extornados!!!");
        } catch (Exception e) {}
        
        try {
            sql = FuncoesGlobais.Subst("DELETE FROM imposto WHERE rc_aut = '&1.'", new String[] {jAutenticacao.getText()});
            conn.ExecutarComando(sql);
            strings = FuncoesGlobais.ArrayAdd(strings, "Imposto Extornados!!!");
        } catch (Exception e) {}
        
        try {
            sql = FuncoesGlobais.Subst("DELETE FROM extrato WHERE rc_aut = '&1.'", new String[] {jAutenticacao.getText()});
            conn.ExecutarComando(sql);
            strings = FuncoesGlobais.ArrayAdd(strings, "Extrato Extornados!!!");
        } catch (Exception e) {}
        
        try {
            sql = FuncoesGlobais.Subst("DELETE FROM DESPESAS WHERE CAST(autentica AS UNSIGNED Int) = &1.", new String[] {jAutenticacao.getText()});
            conn.ExecutarComando(sql);
            strings = FuncoesGlobais.ArrayAdd(strings, "Despesas Extornados!!!");
        } catch (Exception e) {}
        
        try {
            sql = FuncoesGlobais.Subst("DELETE FROM auxiliar WHERE rc_aut = '&1.'", new String[] {jAutenticacao.getText()});
            conn.ExecutarComando(sql);
            strings = FuncoesGlobais.ArrayAdd(strings, "Auxiliar Extornados!!!");
        } catch (Exception e) {}
        
        try {
            sql = FuncoesGlobais.Subst("DELETE FROM caixa WHERE cx_aut = '&1.'", new String[] {jAutenticacao.getText()});
            conn.ExecutarComando(sql);
            strings = FuncoesGlobais.ArrayAdd(strings, "Caixa Extornados!!!");
        } catch (Exception e) {}
        
        try {
            sql = FuncoesGlobais.Subst("DELETE FROM caixabck WHERE cx_aut = '&1.'", new String[] {jAutenticacao.getText()});
            conn.ExecutarComando(sql);
            strings = FuncoesGlobais.ArrayAdd(strings, "Caixabck Extornados!!!");
        } catch (Exception e) {}

        DefaultListModel model = new DefaultListModel();
        for (int i=0;i<strings.length;i++) { model.add(i, strings[i]); }
        jListaExtorno.setModel(model);
        
        JOptionPane.showMessageDialog(null, "Extornado com sucesso!!!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbtExtornarActionPerformed

    private void jbtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtSairActionPerformed

    private void jAutenticacaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jAutenticacaoFocusGained
        jListaExtorno.removeAll();
        jbtExtornar.setEnabled(false);
    }//GEN-LAST:event_jAutenticacaoFocusGained

    private void jAutenticacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jAutenticacaoFocusLost
        jbtExtornar.setEnabled(true);
    }//GEN-LAST:event_jAutenticacaoFocusLost
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAutenticacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jListaExtorno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtExtornar;
    private javax.swing.JButton jbtSair;
    // End of variables declaration//GEN-END:variables
}
