/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jAcessos.java
 *
 * Created on 16/12/2011, 06:01:38
 */

package Sicit.Login;

import Funcoes.DbMain;
import Funcoes.FuncoesGlobais;
import Funcoes.VariaveisGlobais;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JCheckBox;

/**
 *
 * @author mariana
 */
public class jAcessos extends javax.swing.JInternalFrame {
    DbMain conn = VariaveisGlobais.conexao;
    
    /** Creates new form jAcessos */
    public jAcessos() {
        initComponents();

        jUsuarios.setModel(new javax.swing.DefaultComboBoxModel(ListaUsuarios()));

    }

    private String[] ListaUsuarios() {
        ResultSet rst = conn.AbrirTabela("SELECT usuario FROM cadfun ORDER BY f_cod;", ResultSet.CONCUR_READ_ONLY);
        String[] lista = {};
        try {
            while (rst.next()) {
                lista = FuncoesGlobais.ArrayAdd(lista, rst.getString("usuario"));
            }
        } catch (SQLException ex) {}
        DbMain.FecharTabela(rst);

        return lista;
    }

    private Object[] ItensMenu() {

        Object[] itens = {jmnuProprietarios,    //0
                          jmnuLocatarios,       //1
                          jmnuBusca,            //2
                          jmnuRecebimentos,     //3
                          jmnuExtrato,          //4
                          jmnuAvisos,           //5
                          jmnuDespesas,         //6
                          jmnuDepositos,        //7
                          jmnuExtornar,         //8
                          jmnuPassCaixa,        //9
                          jmnuFeCaixa,          //10
                          jmnuAltRecibos,       //11
                          jmnuDescontos,        //12
                          jmnuDiferencas,       //13
                          jmnuSeguros,          //14
                          jmnuBloqueio,         //15
                          jmnuGeracao,          //16
                          jmnuSite,             //17
                          jmnuRelBol,           //18
                          jmnuRelConf,          //19
                          jmnuRelDesp,          //20
                          jmnuRelRazao,         //21
                          jmnuSocios,           //22
                          jmnuMultas,           //23
                          jmnuAdm,              //24
                          jmnuUsuarios,         //25
                          jmnuAcessos,          //26
                          jmnuRelDepositos,     //27
                          jmnuRelMensalao,      //28
                          jmnuRelReajustes,     //29
                          jmnuRelSeguros,       //30
                          jmnuRelSaldoProp,     //31
                          jmnuSuperExtorno,     //32
                          jmnuRelDoctos,        //33
                          jmnuRelDiaVecto,      //34
                          jmnuRelNovosLoca,     //35
                          jmnuDivisao,          //36
                          jmnuRelRetenPg,       //37
                          jmnuRelRecAtr,        //38
                          jmnuControle,         //39
                          jmnuRelPropLoca,      //40
                          jmnuContas,           //41
                          jmnuAltTxs,           //42
                          jmnuRelExtBanco,      //43
                          jmnuDimob,            //44
                          jmnuBloqLoca,         //45
                          jmnuContasControle,   //46
                          jmnuVisita,           //47
                          jmnuRelSegPagos,      //48
                          jmnuBxBol,            //49
                          jmnuAdianta,          //50
                          jmnuRelVazios,        //51
                          jmnuNotaFiscal,       //52
                          jmnuRelAdi,           //53
                          jmnuRelSegADM};       //54
        return itens;
        // jmnuPropInc, jmnuPropExc, jmnuPropAlt,
        //jmnuLocaInc, jmnuLocaExc, jmnuLocaAlt,
        //jmnuAltRecSeg, jmnuAltRecDif, jmnuAltRecDesc,
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jUsuarios = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jReSenha = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jGravar = new javax.swing.JButton();
        jSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jmnuProprietarios = new javax.swing.JCheckBox();
        jmnuPropInc = new javax.swing.JCheckBox();
        jmnuPropAlt = new javax.swing.JCheckBox();
        jmnuPropExc = new javax.swing.JCheckBox();
        jmnuLocatarios = new javax.swing.JCheckBox();
        jmnuLocaInc = new javax.swing.JCheckBox();
        jmnuLocaExc = new javax.swing.JCheckBox();
        jmnuLocaAlt = new javax.swing.JCheckBox();
        jmnuBusca = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jmnuRecebimentos = new javax.swing.JCheckBox();
        jmnuExtrato = new javax.swing.JCheckBox();
        jmnuDespesas = new javax.swing.JCheckBox();
        jmnuAvisos = new javax.swing.JCheckBox();
        jmnuExtornar = new javax.swing.JCheckBox();
        jmnuDepositos = new javax.swing.JCheckBox();
        jmnuPassCaixa = new javax.swing.JCheckBox();
        jmnuFeCaixa = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jmnuAltRecibos = new javax.swing.JCheckBox();
        jmnuRelBol = new javax.swing.JCheckBox();
        jmnuAltRecSeg = new javax.swing.JCheckBox();
        jmnuAltRecDif = new javax.swing.JCheckBox();
        jmnuAltRecDesc = new javax.swing.JCheckBox();
        jmnuDiferencas = new javax.swing.JCheckBox();
        jmnuSeguros = new javax.swing.JCheckBox();
        jmnuBloqueio = new javax.swing.JCheckBox();
        jmnuGeracao = new javax.swing.JCheckBox();
        jmnuSite = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jmnuDescontos = new javax.swing.JCheckBox();
        jmnuRelConf = new javax.swing.JCheckBox();
        jmnuRelDesp = new javax.swing.JCheckBox();
        jmnuRelRazao = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jmnuSocios = new javax.swing.JCheckBox();
        jmnuMultas = new javax.swing.JCheckBox();
        jmnuAdm = new javax.swing.JCheckBox();
        jmnuUsuarios = new javax.swing.JCheckBox();
        jmnuAcessos = new javax.swing.JCheckBox();
        jmnuRelDepositos = new javax.swing.JCheckBox();
        jmnuRelMensalao = new javax.swing.JCheckBox();
        jmnuRelReajustes = new javax.swing.JCheckBox();
        jmnuRelSeguros = new javax.swing.JCheckBox();
        jmnuRelSaldoProp = new javax.swing.JCheckBox();
        jmnuSuperExtorno = new javax.swing.JCheckBox();
        jmnuRelDoctos = new javax.swing.JCheckBox();
        jmnuRelDiaVecto = new javax.swing.JCheckBox();
        jmnuRelNovosLoca = new javax.swing.JCheckBox();
        jmnuDivisao = new javax.swing.JCheckBox();
        jmnuRelRetenPg = new javax.swing.JCheckBox();
        jmnuRelRecAtr = new javax.swing.JCheckBox();
        jmnuControle = new javax.swing.JCheckBox();
        jmnuRelPropLoca = new javax.swing.JCheckBox();
        jmnuContas = new javax.swing.JCheckBox();
        jmnuAltTxs = new javax.swing.JCheckBox();
        jmnuRelExtBanco = new javax.swing.JCheckBox();
        jmnuDimob = new javax.swing.JCheckBox();
        jmnuBloqLoca = new javax.swing.JCheckBox();
        jmnuContasControle = new javax.swing.JCheckBox();
        jmnuVisita = new javax.swing.JCheckBox();
        jmnuRelSegPagos = new javax.swing.JCheckBox();
        jmnuBxBol = new javax.swing.JCheckBox();
        jmnuAdianta = new javax.swing.JCheckBox();
        jmnuRelVazios = new javax.swing.JCheckBox();
        jmnuNotaFiscal = new javax.swing.JCheckBox();
        jmnuRelAdi = new javax.swing.JCheckBox();
        jmnuRelSegADM = new javax.swing.JCheckBox();
        jSenha = new javax.swing.JTextField();

        setClosable(true);
        setTitle(".:: Acessos do sistema");
        setVisible(true);

        jLabel1.setText("Usuário:");

        jUsuarios.setMaximumRowCount(10);
        jUsuarios.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jUsuariosFocusLost(evt);
            }
        });

        jLabel2.setText("Senha:");

        jReSenha.setText("Mudar senha no login");
        jReSenha.setEnabled(false);

        jGravar.setText("Gravar");
        jGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGravarActionPerformed(evt);
            }
        });

        jSair.setText("Sair");
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabel3.setBackground(new java.awt.Color(153, 102, 255));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(".:: Cadastros");
        jLabel3.setOpaque(true);

        jmnuProprietarios.setText("Proprietários");

        jmnuPropInc.setText("Incluir");
        jmnuPropInc.setEnabled(false);

        jmnuPropAlt.setText("Alterar");
        jmnuPropAlt.setEnabled(false);

        jmnuPropExc.setText("Excluir");
        jmnuPropExc.setEnabled(false);

        jmnuLocatarios.setText("Locatários");

        jmnuLocaInc.setText("Incluir");
        jmnuLocaInc.setEnabled(false);

        jmnuLocaExc.setText("Excluir");
        jmnuLocaExc.setEnabled(false);

        jmnuLocaAlt.setText("Alterar");
        jmnuLocaAlt.setEnabled(false);

        jmnuBusca.setText("Busca Global");

        jLabel4.setBackground(new java.awt.Color(153, 102, 255));
        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(".:: Caixa");
        jLabel4.setOpaque(true);

        jmnuRecebimentos.setText("Recebimentos");

        jmnuExtrato.setText("Extratos");

        jmnuDespesas.setText("Despesas");

        jmnuAvisos.setText("Avisos");

        jmnuExtornar.setText("Extornar");

        jmnuDepositos.setText("Depósitos");

        jmnuPassCaixa.setText("Passagem de Caixa");

        jmnuFeCaixa.setText("Fechamento de Caixa");

        jLabel5.setBackground(new java.awt.Color(153, 102, 255));
        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(".:: Movimento");
        jLabel5.setOpaque(true);

        jmnuAltRecibos.setText("Alteração de Recibos");

        jmnuRelBol.setText("Impressão de Boletos Bancários");

        jmnuAltRecSeg.setText("Seguro");
        jmnuAltRecSeg.setEnabled(false);

        jmnuAltRecDif.setText("Diferença");
        jmnuAltRecDif.setEnabled(false);

        jmnuAltRecDesc.setText("Desconto");
        jmnuAltRecDesc.setEnabled(false);

        jmnuDiferencas.setText("Diferenças");

        jmnuSeguros.setText("Seguros");

        jmnuBloqueio.setText("Bloqueio de Recebimentos no Extrato do Proprietário");

        jmnuGeracao.setText("Geração de Movimentos - Boletas/Recibos");

        jmnuSite.setText("Cadastro/Manutenção/Envios Web-Site");

        jLabel6.setBackground(new java.awt.Color(153, 102, 255));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(".:: Relatórios");
        jLabel6.setOpaque(true);

        jmnuDescontos.setText("Descontos");

        jmnuRelConf.setText("Relatório diário de Conferencias");

        jmnuRelDesp.setText("Relatório de Despesas");

        jmnuRelRazao.setText("Relatório Razão");

        jLabel7.setBackground(new java.awt.Color(255, 51, 51));
        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(".:: Gerência");
        jLabel7.setOpaque(true);

        jmnuSocios.setText("Emissão de Extrato de Sócios");

        jmnuMultas.setText("Cadastro de Parametros de Calculos (Multa/Juros/Correções/Taxas/Percentuais)");

        jmnuAdm.setText("Parametros e Dados do Sistema ");

        jmnuUsuarios.setText("Cadastro de Usuários do Sistema");

        jmnuAcessos.setText("Cadastro/Alteração de Senhas e Acessos ao Sistema (Esta Tela)");

        jmnuRelDepositos.setText("Relatório Depósitos");

        jmnuRelMensalao.setText("Relatório Mensalão");

        jmnuRelReajustes.setText("Relatório Reajustes");

        jmnuRelSeguros.setText("Relatório Seguros");
        jmnuRelSeguros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuRelSegurosActionPerformed(evt);
            }
        });

        jmnuRelSaldoProp.setText("Relatórios de Saldos");
        jmnuRelSaldoProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuRelSaldoPropActionPerformed(evt);
            }
        });

        jmnuSuperExtorno.setText("Super EXTORNO");

        jmnuRelDoctos.setText("Visualizar/Imprimir documentos (2ª Via)");

        jmnuRelDiaVecto.setText("Relatório Dias de Vencimentos");

        jmnuRelNovosLoca.setText("Relatório de Novos Locatários");

        jmnuDivisao.setText("Divisão de Conta Corrente");

        jmnuRelRetenPg.setText("Relatório de Retenções");

        jmnuRelRecAtr.setText("Relatório de Recibos em Atraso");

        jmnuControle.setText("Controle de Cheques");

        jmnuRelPropLoca.setText("Relatório de Proprietário e seus Imóveis");

        jmnuContas.setText("Controle de Contas");

        jmnuAltTxs.setText("Atualização de Taxas");

        jmnuRelExtBanco.setText("Relatório de Lançamentos Bancários");

        jmnuDimob.setText("Exportar para DIMOB-RF");

        jmnuBloqLoca.setText("Bloqueio de Recebimentos de Locatários");

        jmnuContasControle.setText("Contas Controle");

        jmnuVisita.setText("Visita ao Imóvel");

        jmnuRelSegPagos.setText("Relatório de Seguros Pagos");

        jmnuBxBol.setText("Baixa de Boletos Bancários");

        jmnuAdianta.setText("Adiantamentos");

        jmnuRelVazios.setText("Relatório de Imóveis Vazios");
        jmnuRelVazios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuRelVaziosActionPerformed(evt);
            }
        });

        jmnuNotaFiscal.setText("Relatório de NotaFiscal");
        jmnuNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuNotaFiscalActionPerformed(evt);
            }
        });

        jmnuRelAdi.setText("Relatório de Adiantamentos");
        jmnuRelAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuRelAdiActionPerformed(evt);
            }
        });

        jmnuRelSegADM.setText("Relatório de Seguros ADM");
        jmnuRelSegADM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuRelSegADMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jmnuUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jmnuControle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jmnuAcessos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jmnuAdm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(112, 112, 112))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jmnuDivisao)
                            .addComponent(jmnuSuperExtorno, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmnuSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmnuMultas)
                            .addComponent(jmnuContas)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jmnuDescontos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jmnuSite, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jmnuGeracao, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jmnuSeguros, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jmnuDiferencas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jmnuFeCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jmnuExtornar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jmnuDepositos, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jmnuDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jmnuExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jmnuLocaInc)
                                        .addGap(26, 26, 26)
                                        .addComponent(jmnuLocaExc)
                                        .addGap(18, 18, 18)
                                        .addComponent(jmnuLocaAlt))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jmnuLocatarios, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jmnuProprietarios, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jmnuBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(93, 93, 93)
                                        .addComponent(jmnuPropInc)
                                        .addGap(26, 26, 26)
                                        .addComponent(jmnuPropExc)
                                        .addGap(18, 18, 18)
                                        .addComponent(jmnuPropAlt)))
                                .addComponent(jmnuRecebimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                                .addComponent(jmnuAvisos, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jmnuPassCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jmnuAltRecibos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38)
                                    .addComponent(jmnuAltRecSeg)
                                    .addGap(26, 26, 26)
                                    .addComponent(jmnuAltRecDif)
                                    .addGap(18, 18, 18)
                                    .addComponent(jmnuAltRecDesc))
                                .addComponent(jmnuBloqueio, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jmnuAltTxs, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jmnuDimob)
                            .addComponent(jmnuBloqLoca, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmnuContasControle, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmnuVisita)
                            .addComponent(jmnuBxBol, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmnuAdianta, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmnuRelRecAtr, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmnuRelNovosLoca)
                            .addComponent(jmnuRelSaldoProp, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmnuRelSeguros, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmnuRelReajustes, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmnuRelMensalao, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmnuRelDepositos, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jmnuRelRazao, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jmnuRelDesp, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jmnuRelConf, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                                .addComponent(jmnuRelBol, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jmnuRelDoctos, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmnuRelDiaVecto)
                            .addComponent(jmnuRelPropLoca, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmnuRelExtBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmnuRelSegPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmnuRelVazios, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmnuNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmnuRelAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmnuRelRetenPg, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmnuRelSegADM, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 13, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmnuProprietarios)
                    .addComponent(jmnuPropInc)
                    .addComponent(jmnuPropAlt)
                    .addComponent(jmnuPropExc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jmnuLocaInc)
                        .addComponent(jmnuLocaAlt)
                        .addComponent(jmnuLocaExc))
                    .addComponent(jmnuLocatarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuBusca)
                .addGap(2, 2, 2)
                .addComponent(jmnuVisita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jmnuRecebimentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuExtrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuAvisos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuDespesas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuDepositos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuExtornar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuPassCaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuFeCaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuBxBol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmnuAltRecibos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmnuAltRecSeg)
                    .addComponent(jmnuAltRecDesc)
                    .addComponent(jmnuAltRecDif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuDescontos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuDiferencas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuSeguros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuBloqueio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuGeracao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuSite)
                .addGap(7, 7, 7)
                .addComponent(jmnuAltTxs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuAdianta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuRelBol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuRelConf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuRelDesp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuRelRazao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuRelDepositos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuRelMensalao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuRelReajustes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuRelSeguros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuRelSaldoProp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuRelDoctos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuRelDiaVecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuRelNovosLoca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuRelRecAtr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuRelRetenPg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuRelPropLoca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuRelExtBanco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuRelSegPagos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuRelVazios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuNotaFiscal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuRelAdi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuRelSegADM)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuSocios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuMultas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuAdm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuAcessos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuSuperExtorno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuDivisao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuControle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuContas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuDimob)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuBloqLoca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmnuContasControle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jReSenha))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jReSenha)
                    .addComponent(jSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSair)
                    .addComponent(jGravar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUsuariosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsuariosFocusLost
        String sql = "SELECT senha, atalhos FROM cadfun Where usuario='&1.'";
        sql = FuncoesGlobais.Subst(sql, new String[] {jUsuarios.getSelectedItem().toString().trim()});
        ResultSet rst = conn.AbrirTabela(sql, ResultSet.CONCUR_READ_ONLY);
        String protocolomenu = "";

        try {
            while (rst.next()) {
                jSenha.setText(rst.getString("senha"));
                protocolomenu = rst.getString("atalhos");
            }
        } catch (SQLException ex) {}

        Ler(protocolomenu);
    }//GEN-LAST:event_jUsuariosFocusLost

    private void jGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGravarActionPerformed
        String protocolomenu = Gravar().trim();
        String usuario = jUsuarios.getSelectedItem().toString().trim();
        String senha = jSenha.getText().trim();

        String sql = "UPDATE cadfun SET senha='&1.', atalhos='&2.' WHERE usuario='&3.';";
        sql = FuncoesGlobais.Subst(sql, new String[] {senha, protocolomenu, usuario});
        conn.ExecutarComando(sql);
    }//GEN-LAST:event_jGravarActionPerformed

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jSairActionPerformed

    private void jmnuRelSegurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuRelSegurosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmnuRelSegurosActionPerformed

    private void jmnuRelSaldoPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuRelSaldoPropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmnuRelSaldoPropActionPerformed

    private void jmnuRelVaziosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuRelVaziosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmnuRelVaziosActionPerformed

    private void jmnuNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuNotaFiscalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmnuNotaFiscalActionPerformed

    private void jmnuRelAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuRelAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmnuRelAdiActionPerformed

    private void jmnuRelSegADMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuRelSegADMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmnuRelSegADMActionPerformed

    private void Ler(String protocolomenu) {
        Object[] mnu = ItensMenu();
        // limpar opções
        for (int i=0;i<mnu.length;i++) { ((JCheckBox) mnu[i]).setSelected(false); }

        if (!"".equals(protocolomenu.trim())) {
            String[] parte1 = protocolomenu.split(";");
            for (int i=0; i<parte1.length;i++) {
                String[] parte2 = parte1[i].split(":");
                ((JCheckBox) mnu[Integer.valueOf(parte2[0])]).setSelected(("1".equals(parte2[1]) ? true : false));
            }
        }
    }

    private String Gravar() {
        Object[] mnu = ItensMenu();
        String protocolomenu = "";
        for (int i=0;i<mnu.length;i++) {
            if (((JCheckBox) mnu[i]).isSelected()) {
                protocolomenu += i + ":1;";
            }
        }
        return protocolomenu.substring(0,protocolomenu.length() - 1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jGravar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jReSenha;
    private javax.swing.JButton jSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSenha;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox jUsuarios;
    private javax.swing.JCheckBox jmnuAcessos;
    private javax.swing.JCheckBox jmnuAdianta;
    private javax.swing.JCheckBox jmnuAdm;
    private javax.swing.JCheckBox jmnuAltRecDesc;
    private javax.swing.JCheckBox jmnuAltRecDif;
    private javax.swing.JCheckBox jmnuAltRecSeg;
    private javax.swing.JCheckBox jmnuAltRecibos;
    private javax.swing.JCheckBox jmnuAltTxs;
    private javax.swing.JCheckBox jmnuAvisos;
    private javax.swing.JCheckBox jmnuBloqLoca;
    private javax.swing.JCheckBox jmnuBloqueio;
    private javax.swing.JCheckBox jmnuBusca;
    private javax.swing.JCheckBox jmnuBxBol;
    private javax.swing.JCheckBox jmnuContas;
    private javax.swing.JCheckBox jmnuContasControle;
    private javax.swing.JCheckBox jmnuControle;
    private javax.swing.JCheckBox jmnuDepositos;
    private javax.swing.JCheckBox jmnuDescontos;
    private javax.swing.JCheckBox jmnuDespesas;
    private javax.swing.JCheckBox jmnuDiferencas;
    private javax.swing.JCheckBox jmnuDimob;
    private javax.swing.JCheckBox jmnuDivisao;
    private javax.swing.JCheckBox jmnuExtornar;
    private javax.swing.JCheckBox jmnuExtrato;
    private javax.swing.JCheckBox jmnuFeCaixa;
    private javax.swing.JCheckBox jmnuGeracao;
    private javax.swing.JCheckBox jmnuLocaAlt;
    private javax.swing.JCheckBox jmnuLocaExc;
    private javax.swing.JCheckBox jmnuLocaInc;
    private javax.swing.JCheckBox jmnuLocatarios;
    private javax.swing.JCheckBox jmnuMultas;
    private javax.swing.JCheckBox jmnuNotaFiscal;
    private javax.swing.JCheckBox jmnuPassCaixa;
    private javax.swing.JCheckBox jmnuPropAlt;
    private javax.swing.JCheckBox jmnuPropExc;
    private javax.swing.JCheckBox jmnuPropInc;
    private javax.swing.JCheckBox jmnuProprietarios;
    private javax.swing.JCheckBox jmnuRecebimentos;
    private javax.swing.JCheckBox jmnuRelAdi;
    private javax.swing.JCheckBox jmnuRelBol;
    private javax.swing.JCheckBox jmnuRelConf;
    private javax.swing.JCheckBox jmnuRelDepositos;
    private javax.swing.JCheckBox jmnuRelDesp;
    private javax.swing.JCheckBox jmnuRelDiaVecto;
    private javax.swing.JCheckBox jmnuRelDoctos;
    private javax.swing.JCheckBox jmnuRelExtBanco;
    private javax.swing.JCheckBox jmnuRelMensalao;
    private javax.swing.JCheckBox jmnuRelNovosLoca;
    private javax.swing.JCheckBox jmnuRelPropLoca;
    private javax.swing.JCheckBox jmnuRelRazao;
    private javax.swing.JCheckBox jmnuRelReajustes;
    private javax.swing.JCheckBox jmnuRelRecAtr;
    private javax.swing.JCheckBox jmnuRelRetenPg;
    private javax.swing.JCheckBox jmnuRelSaldoProp;
    private javax.swing.JCheckBox jmnuRelSegADM;
    private javax.swing.JCheckBox jmnuRelSegPagos;
    private javax.swing.JCheckBox jmnuRelSeguros;
    private javax.swing.JCheckBox jmnuRelVazios;
    private javax.swing.JCheckBox jmnuSeguros;
    private javax.swing.JCheckBox jmnuSite;
    private javax.swing.JCheckBox jmnuSocios;
    private javax.swing.JCheckBox jmnuSuperExtorno;
    private javax.swing.JCheckBox jmnuUsuarios;
    private javax.swing.JCheckBox jmnuVisita;
    // End of variables declaration//GEN-END:variables

}
