/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jProprietarios.java
 *
 * Created on 26/01/2011, 18:21:23
 */

package Sici;

import Funcoes.TableControl;
import Funcoes.DbMain;
import Funcoes.FuncoesGlobais;
import Funcoes.LimitedTextField;
import Funcoes.ValidaFisicaJuridica;
import Funcoes.VariaveisGlobais;
import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author supervisor
 */
public class jVisita extends javax.swing.JInternalFrame {
    DbMain conn = VariaveisGlobais.conexao;
    ResultSet pResult = conn.AbrirTabela("SELECT * FROM proprietarios ORDER BY rgprp;", ResultSet.CONCUR_UPDATABLE);
    private boolean bNew = false;
    
    /** Creates new form jProprietarios */
    public jVisita() throws SQLException {
        /**
         * Icone do modulo
         */
        ImageIcon icone = new ImageIcon("Figuras/prop.png");
        //setIconImage(icone.getImage());

        initComponents();
        LerDados(true);

        // Colocando enter para pular de campo
        HashSet conj = new HashSet(this.getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        this.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);

        mCpf.setVisible(true);
        mCnpj.setVisible(false);
        
        mNome.requestFocus();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mCodigo = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        mNome = new LimitedTextField(60);
        mTipoDoc = new LimitedTextField(1);
        jLabel3 = new javax.swing.JLabel();
        mEndereco = new LimitedTextField(60);
        jLabel4 = new javax.swing.JLabel();
        mNumero = new LimitedTextField(10);
        jLabel5 = new javax.swing.JLabel();
        mCplto = new LimitedTextField(15);
        jLabel6 = new javax.swing.JLabel();
        mBairro = new LimitedTextField(25);
        jLabel7 = new javax.swing.JLabel();
        mCidade = new LimitedTextField(25);
        jLabel8 = new javax.swing.JLabel();
        mEstado = new LimitedTextField(2);
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mTelefone = new LimitedTextField(14);
        jLabel11 = new javax.swing.JLabel();
        mProfissao = new LimitedTextField(25);
        jLabel12 = new javax.swing.JLabel();
        mRepresentante = new LimitedTextField(60);
        jLabel13 = new javax.swing.JLabel();
        mDtNascRep = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
        jLabel14 = new javax.swing.JLabel();
        mNacionalidade = new LimitedTextField(25);
        jLabel15 = new javax.swing.JLabel();
        mEstCivil = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        mDtNasc = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
        jLabel17 = new javax.swing.JLabel();
        mIdentidade = new LimitedTextField(20);
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        mConjugue = new LimitedTextField(60);
        jLabel20 = new javax.swing.JLabel();
        mDtNascConj = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
        jLabel21 = new javax.swing.JLabel();
        mBanco = new LimitedTextField(5);
        jLabel22 = new javax.swing.JLabel();
        mAgencia = new LimitedTextField(5);
        jLabel23 = new javax.swing.JLabel();
        mCCorrente = new LimitedTextField(10);
        jLabel24 = new javax.swing.JLabel();
        mFavorecido = new LimitedTextField(60);
        jLabel25 = new javax.swing.JLabel();
        mEmail = new LimitedTextField(60);
        jScrollPane1 = new javax.swing.JScrollPane();
        tbvImoveis = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        mDtEntrada = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
        jLabel27 = new javax.swing.JLabel();
        mDtSaida = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
        jLabel28 = new javax.swing.JLabel();
        mStatus = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        mMSgBoleta = new LimitedTextField(60);
        jLabel30 = new javax.swing.JLabel();
        mMsgRecibo = new LimitedTextField(60);
        jLabel31 = new javax.swing.JLabel();
        mObsCaixa = new LimitedTextField(60);
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cbxEnviar = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();
        mEnderecoEnv = new LimitedTextField(60);
        jLabel33 = new javax.swing.JLabel();
        mNumeroEnv = new LimitedTextField(10);
        jLabel34 = new javax.swing.JLabel();
        mCpltoEnv = new LimitedTextField(15);
        jLabel35 = new javax.swing.JLabel();
        mBairroEnv = new LimitedTextField(25);
        jLabel36 = new javax.swing.JLabel();
        mCidadeEnv = new LimitedTextField(25);
        jLabel37 = new javax.swing.JLabel();
        mEstadoEnv = new LimitedTextField(2);
        jLabel38 = new javax.swing.JLabel();
        mCepEnv = new LimitedTextField(9);
        jPanel3 = new javax.swing.JPanel();
        btIncluir = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btGravar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btTras = new javax.swing.JButton();
        btFrente = new javax.swing.JButton();
        btIrPara = new javax.swing.JButton();
        btImoveis = new javax.swing.JButton();
        mCep = new javax.swing.JFormattedTextField();
        mCpf = new javax.swing.JFormattedTextField();
        mCnpj = new javax.swing.JFormattedTextField();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setText("Código:");

        setClosable(true);
        setIconifiable(true);
        setTitle(".:: Cadastro de Proprietários ::.");
        setToolTipText("Cadastro de Proprietários");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/prop.png"))); // NOI18N
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameIconified(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.setLayout(null);

        mCodigo.setEditable(false);
        mCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mCodigo.setToolTipText("Código do Proprietário...");
        mCodigo.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mCodigo.setName("mRgprp"); // NOI18N
        mCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCodigoActionPerformed(evt);
            }
        });
        mCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mCodigoFocusLost(evt);
            }
        });
        jPanel1.add(mCodigo);
        mCodigo.setBounds(20, 10, 60, 17);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 10, 25, 10);

        mNome.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mNome.setName("mNome"); // NOI18N
        mNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mNomeFocusLost(evt);
            }
        });
        jPanel1.add(mNome);
        mNome.setBounds(130, 10, 420, 16);

        mTipoDoc.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        mTipoDoc.setInputVerifier(new ValidaFisicaJuridica(mTipoDoc, mCpf, mCnpj));
        mTipoDoc.setName("mTipoDoc"); // NOI18N
        mTipoDoc.setNextFocusableComponent(mEndereco);
        mTipoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTipoDocActionPerformed(evt);
            }
        });
        mTipoDoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mTipoDocFocusLost(evt);
            }
        });
        jPanel1.add(mTipoDoc);
        mTipoDoc.setBounds(560, 10, 20, 16);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel3.setText("Endereço:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 30, 38, 20);

        mEndereco.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mEndereco.setName("mEndereco"); // NOI18N
        jPanel1.add(mEndereco);
        mEndereco.setBounds(50, 30, 340, 16);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel4.setText("N°.:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(400, 30, 14, 10);

        mNumero.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mNumero.setName("mNumero"); // NOI18N
        jPanel1.add(mNumero);
        mNumero.setBounds(420, 30, 53, 16);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel5.setText("Cplto:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(480, 30, 24, 10);

        mCplto.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mCplto.setName("mCplto"); // NOI18N
        jPanel1.add(mCplto);
        mCplto.setBounds(510, 30, 70, 16);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel6.setText("Bairro:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 50, 26, 20);

        mBairro.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mBairro.setName("mBairro"); // NOI18N
        jPanel1.add(mBairro);
        mBairro.setBounds(40, 50, 140, 16);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel7.setText("Cidade:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 50, 29, 20);

        mCidade.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mCidade.setName("mCidade"); // NOI18N
        jPanel1.add(mCidade);
        mCidade.setBounds(230, 50, 158, 16);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel8.setText("UF:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(400, 50, 14, 20);

        mEstado.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mEstado.setName("mEstado"); // NOI18N
        jPanel1.add(mEstado);
        mEstado.setBounds(420, 50, 30, 16);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel9.setText("Cep:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(460, 50, 18, 20);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel10.setText("Telefone:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 70, 35, 10);

        mTelefone.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        mTelefone.setName("mTelefone"); // NOI18N
        jPanel1.add(mTelefone);
        mTelefone.setBounds(50, 70, 146, 16);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel11.setText("Profissão:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(200, 70, 38, 10);

        mProfissao.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        mProfissao.setName("mProfissao"); // NOI18N
        jPanel1.add(mProfissao);
        mProfissao.setBounds(240, 70, 340, 16);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel12.setText("Representante:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 90, 57, 10);

        mRepresentante.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jPanel1.add(mRepresentante);
        mRepresentante.setBounds(70, 90, 290, 16);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel13.setText("Dt.Nasc.:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(410, 90, 34, 10);

        mDtNascRep.setDate(new java.util.Date(-2208977612000L));
        mDtNascRep.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jPanel1.add(mDtNascRep);
        mDtNascRep.setBounds(460, 90, 120, 20);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel14.setText("Nacionalidade:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 110, 55, 10);

        mNacionalidade.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mNacionalidade.setName("mNacionalidade"); // NOI18N
        jPanel1.add(mNacionalidade);
        mNacionalidade.setBounds(70, 110, 170, 16);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel15.setText("E.Civil:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(250, 110, 26, 10);

        mEstCivil.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        mEstCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteriro(a)", "Casado(a)", "Separado(a)", "Divorciado(a)", "Viuvo(a)" }));
        mEstCivil.setName("mEstCivil"); // NOI18N
        jPanel1.add(mEstCivil);
        mEstCivil.setBounds(280, 110, 121, 17);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel16.setText("Dt.Nasc.:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(410, 110, 34, 10);

        mDtNasc.setDate(new java.util.Date(-2208977612000L));
        mDtNasc.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jPanel1.add(mDtNasc);
        mDtNasc.setBounds(470, 110, 110, 20);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel17.setText("R.G.:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(10, 130, 19, 10);

        mIdentidade.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mIdentidade.setName("mIdentidade"); // NOI18N
        jPanel1.add(mIdentidade);
        mIdentidade.setBounds(50, 130, 200, 16);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel18.setText("CPF/CNPJ:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(270, 130, 42, 10);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel19.setText("Conjugue:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(10, 150, 40, 10);

        mConjugue.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mConjugue.setName("mConjugue"); // NOI18N
        jPanel1.add(mConjugue);
        mConjugue.setBounds(50, 150, 280, 16);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel20.setText("Dt.Nasc.:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(340, 150, 34, 10);

        mDtNascConj.setDate(new java.util.Date(-2208977612000L));
        mDtNascConj.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jPanel1.add(mDtNascConj);
        mDtNascConj.setBounds(450, 150, 129, 20);

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel21.setText("Banco:");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(10, 170, 27, 10);

        mBanco.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mBanco.setName("mBanco"); // NOI18N
        jPanel1.add(mBanco);
        mBanco.setBounds(60, 170, 62, 16);

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel22.setText("Agência:");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(140, 170, 33, 10);

        mAgencia.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mAgencia.setName("mAgencia"); // NOI18N
        jPanel1.add(mAgencia);
        mAgencia.setBounds(180, 170, 89, 16);

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel23.setText("Conta Corrente:");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(270, 170, 61, 10);

        mCCorrente.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mCCorrente.setName("mCCorrente"); // NOI18N
        jPanel1.add(mCCorrente);
        mCCorrente.setBounds(330, 170, 250, 16);

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel24.setText("Favorecido:");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(10, 190, 44, 10);

        mFavorecido.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mFavorecido.setName("mFavorecido"); // NOI18N
        jPanel1.add(mFavorecido);
        mFavorecido.setBounds(60, 190, 520, 16);

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel25.setText("E-Mail:");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(10, 210, 26, 20);

        mEmail.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        mEmail.setName("mEmail"); // NOI18N
        mEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmailActionPerformed(evt);
            }
        });
        jPanel1.add(mEmail);
        mEmail.setBounds(60, 210, 520, 21);

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N

        tbvImoveis.setAutoCreateRowSorter(true);
        tbvImoveis.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 48, 255)));
        tbvImoveis.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        tbvImoveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbvImoveis.setDoubleBuffered(true);
        tbvImoveis.setName("tbvImoveis"); // NOI18N
        tbvImoveis.setSelectionBackground(new java.awt.Color(244, 255, 0));
        tbvImoveis.setSelectionForeground(new java.awt.Color(255, 0, 0));
        tbvImoveis.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbvImoveis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbvImoveisMouseClicked(evt);
            }
        });
        tbvImoveis.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbvImoveisPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tbvImoveis);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 360, 720, 70);

        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(174, 182, 253), new java.awt.Color(179, 179, 179), null));
        jPanel4.setOpaque(false);

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel26.setText("Dt.Saida:");

        mDtEntrada.setDate(new java.util.Date(-2208977612000L));
        mDtEntrada.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel27.setText("Status:");

        mDtSaida.setDate(new java.util.Date(-2208977612000L));
        mDtSaida.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel28.setText("Dt.Entrada:");

        mStatus.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        mStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel29.setText("Msg Boleta:");

        mMSgBoleta.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mMSgBoleta.setName("mMsgBoleta"); // NOI18N

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel30.setText("Msg Recibo:");

        mMsgRecibo.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mMsgRecibo.setName("mMsgRecibo"); // NOI18N

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel31.setText("Obs Caixa:");

        mObsCaixa.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mObsCaixa.setName("mObsCaixa"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mDtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(14, 14, 14)
                                .addComponent(mStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mMSgBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mMsgRecibo, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mDtSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mObsCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mDtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mMSgBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel27)
                                        .addComponent(mStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mMsgRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel30)))))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mObsCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel31))
                            .addComponent(mDtSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Menssagens", jPanel7);

        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbxEnviar.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        cbxEnviar.setText("Enviar Correspondências para o endereço abaixo:");

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel32.setText("Endereço:");

        mEnderecoEnv.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mEnderecoEnv.setName("mEnderecoEnv"); // NOI18N

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel33.setText("N°.:");

        mNumeroEnv.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mNumeroEnv.setName("mNumeroEnv"); // NOI18N

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel34.setText("Cplto:");

        mCpltoEnv.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mCpltoEnv.setName("mCpltoEnv"); // NOI18N

        jLabel35.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel35.setText("Bairro:");

        mBairroEnv.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mBairroEnv.setName("mBairroEnv"); // NOI18N

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel36.setText("Cidade:");

        mCidadeEnv.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mCidadeEnv.setName("mCidadeEnv"); // NOI18N

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel37.setText("UF:");

        mEstadoEnv.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mEstadoEnv.setName("mEstadoEnv"); // NOI18N

        jLabel38.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel38.setText("Cep:");

        mCepEnv.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mCepEnv.setName("mCepEnv"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(cbxEnviar))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mEnderecoEnv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel33)
                        .addGap(12, 12, 12)
                        .addComponent(mNumeroEnv, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel34)
                        .addGap(3, 3, 3)
                        .addComponent(mCpltoEnv, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mBairroEnv, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel36)
                        .addGap(12, 12, 12)
                        .addComponent(mCidadeEnv, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel37)
                        .addGap(12, 12, 12)
                        .addComponent(mEstadoEnv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38)
                        .addGap(12, 12, 12)
                        .addComponent(mCepEnv, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(cbxEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mNumeroEnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mCpltoEnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel33)
                                .addComponent(jLabel34))))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mEnderecoEnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mBairroEnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel35))
                    .addComponent(mCidadeEnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEstadoEnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mCepEnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Correspondência", jPanel2);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 240, 720, 110);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(138, 137, 149), null, null));
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N

        btIncluir.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        btIncluir.setText("Incluir");
        btIncluir.setName("btIncluir"); // NOI18N
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setName("btExcluir"); // NOI18N

        btGravar.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        btGravar.setText("Gravar");
        btGravar.setName("btGravar"); // NOI18N
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        btSair.setText("Sair");
        btSair.setName("btSair"); // NOI18N
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btTras.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        btTras.setText("<<");
        btTras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTrasActionPerformed(evt);
            }
        });

        btFrente.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        btFrente.setText(">>");
        btFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFrenteActionPerformed(evt);
            }
        });

        btIrPara.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        btIrPara.setText("Ir Para");
        btIrPara.setName("btIrPara"); // NOI18N
        btIrPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIrParaActionPerformed(evt);
            }
        });

        btImoveis.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        btImoveis.setText("Imóveis");
        btImoveis.setName("btImoveis"); // NOI18N
        btImoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImoveisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btTras, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btFrente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btIrPara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btImoveis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btGravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTras)
                    .addComponent(btFrente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btIrPara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btImoveis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSair)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(590, 10, 130, 220);

        try {
            mCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        mCep.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jPanel1.add(mCep);
        mCep.setBounds(480, 50, 100, 16);

        try {
            mCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        mCpf.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        mCpf.setName("mCpf"); // NOI18N
        mCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mCpfFocusGained(evt);
            }
        });
        jPanel1.add(mCpf);
        mCpf.setBounds(310, 130, 230, 16);

        try {
            mCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        mCnpj.setName("mCnpj"); // NOI18N
        mCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mCnpjFocusGained(evt);
            }
        });
        jPanel1.add(mCnpj);
        mCnpj.setBounds(310, 130, 230, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mCodigoFocusLost
        boolean achei = false;
        try {
            achei = MoveToProp("rgprp", mCodigo.getText());
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        if (!achei) {
        }
        mCodigo.setEditable(false);
}//GEN-LAST:event_mCodigoFocusLost

    private void mNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mNomeFocusGained
        mNome.selectAll();
}//GEN-LAST:event_mNomeFocusGained

    private void mNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mNomeFocusLost
        mNome.select(0, 0);
}//GEN-LAST:event_mNomeFocusLost

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        if (bNew) {
            try {
                LerDados(false);
                btIncluir.setEnabled(true);
                btExcluir.setEnabled(true);
                btGravar.setEnabled(true);
                btTras.setEnabled(true);
                btFrente.setEnabled(true);
                btIrPara.setEnabled(true);
                btImoveis.setEnabled(true);
                btSair.setEnabled(true);
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            bNew = false;
        } else this.dispose();
}//GEN-LAST:event_btSairActionPerformed

    private void btTrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTrasActionPerformed
        try {
            boolean previous = pResult.previous();
            if (previous) LerDados(false);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
}//GEN-LAST:event_btTrasActionPerformed

    private void btFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFrenteActionPerformed
        try {
            boolean next = pResult.next();
            if (next) LerDados(false);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
}//GEN-LAST:event_btFrenteActionPerformed

    private void btIrParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIrParaActionPerformed
        mCodigo.setEditable(true);
        mCodigo.selectAll();
        mCodigo.requestFocus();
}//GEN-LAST:event_btIrParaActionPerformed

    private void btImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImoveisActionPerformed
        int selRow = tbvImoveis.getSelectedRow();
        Object valor = null;
        if (selRow > -1) valor = tbvImoveis.getModel().getValueAt(selRow, 0);
        VariaveisGlobais.rgprp = mCodigo.getText();
        VariaveisGlobais.rgimv = (valor != null ? valor.toString() : "0");
                
        jImovel oImv = null;
        try {
            oImv = new jImovel(null, closable);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        oImv.setVisible(true);
        FillImoveis(tbvImoveis, mCodigo.getText());
}//GEN-LAST:event_btImoveisActionPerformed

    private void formInternalFrameIconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameIconified
        //
    }//GEN-LAST:event_formInternalFrameIconified

    private void jPanel1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1AncestorMoved

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        LimpaDados();
        bNew = true;
        btIncluir.setEnabled(false);
        btExcluir.setEnabled(false);
        btGravar.setEnabled(true);
        btTras.setEnabled(false);
        btFrente.setEnabled(false);
        btIrPara.setEnabled(false);
        btImoveis.setEnabled(false);
        btSair.setEnabled(true);

        mNome.requestFocus();
    }//GEN-LAST:event_btIncluirActionPerformed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed

        if (mNome.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Campo 'NOME' nào pode ser vazio!!!", "Erro", JOptionPane.ERROR_MESSAGE);
            mNome.requestFocus();
            return;
        }

        if (mTipoDoc.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Campo 'TIPO' nào pode ser vazio!!!", "Erro", JOptionPane.ERROR_MESSAGE);
            mTipoDoc.requestFocus();
            return;
        }

        if (mCpf.getText().trim().replace(".", "").replace("-", "").replace("/", "").length() == 0) {
            JOptionPane.showMessageDialog(null, "Campo 'CPF' nào pode ser vazio!!!", "Erro", JOptionPane.ERROR_MESSAGE);
            mCpf.requestFocus();
            return;
        }


        if (mCnpj.getText().trim().replace(".", "").replace("-", "").replace("/", "").length() == 0) {
            JOptionPane.showMessageDialog(null, "Campo 'CNPJ' nào pode ser vazio!!!", "Erro", JOptionPane.ERROR_MESSAGE);
            mCnpj.requestFocus();
            return;
        }

        if (mStatus.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(null, "Campo 'STATUS' nào pode ser vazio!!!", "Erro", JOptionPane.ERROR_MESSAGE);
            mStatus.requestFocus();
            return;
        }

        if (mDtEntrada.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Campo 'DATA DE ENTRADA' nào pode ser vazio!!!", "Erro", JOptionPane.ERROR_MESSAGE);
            mDtEntrada.requestFocus();
            return;
        }

        if (mDtNasc.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Campo 'DATA DE NASCIMENTO' nào pode ser vazio!!!", "Erro", JOptionPane.ERROR_MESSAGE);
            mDtNasc.requestFocus();
            return;
        }

        try {
            GravarDados();
        } catch (SQLException ex) { ex.printStackTrace();}

        bNew = false;

        btIncluir.setEnabled(true);
        btExcluir.setEnabled(true);
        btGravar.setEnabled(true);
        btTras.setEnabled(true);
        btFrente.setEnabled(true);
        btIrPara.setEnabled(true);
        btImoveis.setEnabled(true);
        btSair.setEnabled(true);

    }//GEN-LAST:event_btGravarActionPerformed

    private void mTipoDocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mTipoDocFocusLost
    }//GEN-LAST:event_mTipoDocFocusLost

    private void mCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mCpfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_mCpfFocusGained

    private void mCnpjFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mCnpjFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_mCnpjFocusGained

    private void mTipoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTipoDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mTipoDocActionPerformed

    private void tbvImoveisPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbvImoveisPropertyChange
    }//GEN-LAST:event_tbvImoveisPropertyChange

    private void tbvImoveisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbvImoveisMouseClicked
    }//GEN-LAST:event_tbvImoveisMouseClicked

    private void mCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mCodigoActionPerformed

    private void mEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mEmailActionPerformed

    private void GravarDados() throws SQLException {
        SimpleDateFormat fm = new SimpleDateFormat("yyyy/MM/dd");

        String tmpDtEntrada = "0000-00-00";
        try {
            tmpDtEntrada = fm.format(mDtEntrada.getDate()).toString();
        } catch (Exception ex) {}

        String tmpDtSaida = "0000-00-00";
        try {
            tmpDtSaida = fm.format(mDtSaida.getDate()).toString();
        } catch (Exception ex) {}

        String tmpDtNasc = "0000-00-00";
        try {
            tmpDtNasc = fm.format(mDtNasc.getDate());
        } catch (Exception ex) {}

        int iNewRgPrp = 0;
        if (bNew) {
            int NewRgPrp = 0;
            try {
                NewRgPrp = Integer.parseInt(conn.LerParametros("PROP"));
            } catch (SQLException ex) {}
            int PropInc = 0;
            try {
                PropInc = Integer.parseInt(conn.LerParametros("PROPINC"));
            } catch (SQLException ex) {}
            iNewRgPrp = NewRgPrp + PropInc;

            String cPar[] = {"PROP",String.valueOf(iNewRgPrp),"NUMERICO"};
            try {
                conn.GravarParametros(cPar);
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        } else iNewRgPrp = Integer.parseInt(mCodigo.getText());

        if (bNew) {
            pResult.moveToInsertRow();
            pResult.updateInt("rgprp", iNewRgPrp);
        }
        
        pResult.updateString("nome", mNome.getText());
        pResult.updateString("tipoprop", mTipoDoc.getText());
        pResult.updateString("end", mEndereco.getText());
        pResult.updateString("num", mNumero.getText());
        pResult.updateString("compl", mCplto.getText());
        pResult.updateString("bairro", mBairro.getText());
        pResult.updateString("cidade",mCidade.getText());
        pResult.updateString("estado",mEstado.getText());
        pResult.updateString("cep",mCep.getText());
        pResult.updateString("tel",mTelefone.getText());
        pResult.updateString("profissao",mProfissao.getText());
        pResult.updateString("representante",mRepresentante.getText());
        pResult.updateDate("repdtnasc", (java.sql.Date) mDtNascRep.getDate());
        pResult.updateString("naciona",mNacionalidade.getText());
        pResult.updateString("ecivil", mEstCivil.getSelectedItem().toString());
        pResult.updateString("dtnasc", tmpDtNasc);
        pResult.updateString("rginsc",mIdentidade.getText());

        if (mTipoDoc.getText().contains("F")) {
            pResult.updateString("cpfcnpj",mCpf.getText());
        } else
            pResult.updateString("cpfcnpj", mCnpj.getText());
       
        pResult.updateString("conjugue",mConjugue.getText());
        pResult.updateDate("conjdtnasc", (java.sql.Date) mDtNascConj.getDate());
        pResult.updateString("banco", mBanco.getText());
        pResult.updateString("agencia", mAgencia.getText());
        pResult.updateString("conta", mCCorrente.getText());
        pResult.updateString("favorecido", mFavorecido.getText());
        pResult.updateString("email", mEmail.getText());
        pResult.updateString("dtcadastro", tmpDtEntrada);
        pResult.updateString("status", mStatus.getSelectedItem().toString());
        pResult.updateString("dtsaida", tmpDtSaida);
        pResult.updateString("msgboleta", mMSgBoleta.getText());
        pResult.updateString("msgrecibo", mMsgRecibo.getText());
        pResult.updateString("obscaixa", mObsCaixa.getText());
        pResult.updateInt("correio",((cbxEnviar.isSelected()) ? -1 : 0));
        pResult.updateString("cor_end",mEnderecoEnv.getText());
        pResult.updateString("cor_num", mNumeroEnv.getText());
        pResult.updateString("cor_compl",mCpltoEnv.getText());
        pResult.updateString("cor_bairro",mBairroEnv.getText());
        pResult.updateString("cor_cidade", mCidadeEnv.getText());
        pResult.updateString("cor_estado", mEstadoEnv.getText());
        pResult.updateString("cor_cep", mCepEnv.getText());

        if (bNew) {
            pResult.updateString("dtultpagto", "0000-00-00");
            pResult.updateFloat("vrultpagto", 0);
            pResult.updateFloat("saldoant", 0);
            
            mCodigo.setText(Integer.toString(iNewRgPrp));
            pResult.insertRow();
        } else {
            pResult.updateRow();
        }

    }
    
    public boolean MoveToProp(String campo, String seek) throws SQLException {
        boolean achei = false;
        pResult.first();
        while (pResult.next()) {
            if (pResult.getInt(campo) == Integer.parseInt(seek)) {
                achei = true;
                break;
            }
        }
        if (!achei) pResult.first();
        LerDados(false);
        return achei;
    }

    private void LimpaDados() {
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");

        mCodigo.setText("");
        mNome.setText("");
        mTipoDoc.setText("");
        mEndereco.setText("");
        mNumero.setText("");
        mCplto.setText("");
        mBairro.setText("");
        mCidade.setText("");
        mEstado.setText("");
        mCep.setText("");
        mTelefone.setText("");
        mProfissao.setText("");
        mRepresentante.setText("");

        Date DataFormat = null;
        mDtNascRep.setDate(DataFormat);

        mNacionalidade.setText("");
        mEstCivil.setSelectedIndex(0);

        Date DataFormat2 = null;
        mDtNasc.setDate(DataFormat2);

        mIdentidade.setText("");
        mCpf.setText("");
        mConjugue.setText("");

        Date DataFormat3 = null;
        mDtNascConj.setDate(DataFormat3);

        mBanco.setText("");
        mAgencia.setText("");
        mCCorrente.setText("");
        mFavorecido.setText("");
        mEmail.setText("");

        Date DataFormat4 = null;
        mDtEntrada.setDate(DataFormat4);

        mStatus.setSelectedIndex(0);

        Date DataFormat5 = null;
        mDtSaida.setDate(DataFormat5);

        mMSgBoleta.setText("");
        mMsgRecibo.setText("");
        mObsCaixa.setText("");

        cbxEnviar.setSelected(false);
        mEnderecoEnv.setText("");
        mNumeroEnv.setText("");
        mCpltoEnv.setText("");
        mBairroEnv.setText("");
        mCidadeEnv.setText("");
        mEstadoEnv.setText("");
        mCepEnv.setText("");

        // Limpa a lista de imoveis
        TableControl.header(tbvImoveis, new String[][] {{"rgimv","tipoimovel","endereço","situação"},{"50","120","500","100"}});
    }

    private void LerDados(boolean bFirst) throws SQLException {
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");

        if (bFirst) pResult.first();
        mCodigo.setText(String.valueOf(pResult.getInt("rgprp")));
        mNome.setText(pResult.getString("nome"));
        mTipoDoc.setText(pResult.getString("tipoprop"));
        mEndereco.setText(pResult.getString("end"));
        mNumero.setText(pResult.getString("num"));
        mCplto.setText(pResult.getString("compl"));
        mBairro.setText(pResult.getString("bairro"));
        mCidade.setText(pResult.getString("cidade"));
        mEstado.setText(pResult.getString("estado"));
        mCep.setText(pResult.getString("cep"));
        mTelefone.setText(pResult.getString("tel"));
        mProfissao.setText(pResult.getString("profissao"));
        mRepresentante.setText(pResult.getString("representante"));

        Date DataFormat = null;
        try
        {
            DataFormat = pResult.getDate("repdtnasc");
        } catch (SQLException ex) {}
        mDtNascRep.setDate(DataFormat);     //.setText(DataFormat);

        mNacionalidade.setText(pResult.getString("naciona"));

        String pCivil = pResult.getString("ecivil").trim().toLowerCase();
        String sCivil[] = {"solteiro","solteira","casado","casada","separado","separada","divorciado","divorciada","viuvo","viuva"};
        Integer nPos = FuncoesGlobais.IndexOf(sCivil,pCivil) ;
        if (nPos == -1) {
            nPos = 0;
        }
        else if (nPos == 0 || nPos == 1){
            nPos = 0;
        }
        else if (nPos == 2 || nPos == 3) {
            nPos = 1;
        }
        else if (nPos == 4 || nPos == 5) {
            nPos = 2;
        }
        else if (nPos == 6 || nPos == 7) {
            nPos = 3;
        }
        else if (nPos == 8 || nPos == 9 ) {
            nPos = 4;
        }
        else
            nPos = 0;

        mEstCivil.setSelectedIndex(nPos);

        Date DataFormat2 = null;
        try
        {
                DataFormat2 = pResult.getDate("dtnasc");
        } catch (SQLException ex ){}
        mDtNasc.setDate(DataFormat2);

        mIdentidade.setText(pResult.getString("rginsc"));

        if (pResult.getString("tipoprop").contains("F")) {
            mCpf.setText(pResult.getString("cpfcnpj"));
            mCpf.setVisible(true);
            mCnpj.setVisible(false);
        } else {
            mCnpj.setText(pResult.getString("cpfcnpj"));
            mCnpj.setVisible(true);
            mCpf.setVisible(false);
        }

        mConjugue.setText(pResult.getString("conjugue"));

        Date DataFormat3 = null;
        try {
            DataFormat3 = pResult.getDate("conjdtnasc");
        } catch (SQLException ex) {}
        mDtNascConj.setDate(DataFormat3);

        mBanco.setText(pResult.getString("banco"));
        mAgencia.setText(pResult.getString("agencia"));
        mCCorrente.setText(pResult.getString("conta"));
        mFavorecido.setText(pResult.getString("favorecido"));
        mEmail.setText(pResult.getString("email"));

        Date DataFormat4 = null;
        try {
                DataFormat4 = pResult.getDate("dtcadastro");
        } catch (SQLException ex) {}
        mDtEntrada.setDate(DataFormat4);

        String pTipo = pResult.getString("status").trim().toLowerCase();
        String aTipo[] = {"ativo","inativo"};
        nPos = FuncoesGlobais.IndexOf(aTipo, pTipo);
        mStatus.setSelectedIndex(nPos);

        Date DataFormat5 = null;
        try {
            DataFormat5 = pResult.getDate("dtsaida");
        } catch (SQLException ex) {}
        mDtSaida.setDate(DataFormat5);

        mMSgBoleta.setText(pResult.getString("msgboleta"));
        mMsgRecibo.setText(pResult.getString("msgrecibo"));
        mObsCaixa.setText(pResult.getString("obscaixa"));

        cbxEnviar.setSelected(pResult.getBoolean("correio"));
        mEnderecoEnv.setText(pResult.getString("cor_end"));
        mNumeroEnv.setText(pResult.getString("cor_num"));
        mCpltoEnv.setText(pResult.getString("cor_compl"));
        mBairroEnv.setText(pResult.getString("cor_bairro"));
        mCidadeEnv.setText(pResult.getString("cor_cidade"));
        mEstadoEnv.setText(pResult.getString("cor_estado"));
        mCepEnv.setText(pResult.getString("cor_cep"));

        FillImoveis(tbvImoveis, String.valueOf(pResult.getInt("rgprp")));
    }

    private void FillImoveis(JTable table, String rgprp) {
        // Seta Cabecario
        TableControl.header(table, new String[][] {{"rgimv","tipoimovel","endereço","situação"},{"50","120","500","100"}});

        String sSql = "SELECT * FROM imoveis WHERE rgprp = '" + rgprp + "' ORDER BY rgprp, rgimv;";
        ResultSet imResult = this.conn.AbrirTabela(sSql, ResultSet.CONCUR_READ_ONLY);

        try {
            while (imResult.next()) {
                String trgimv = String.valueOf(imResult.getInt("rgimv"));
                String ttpimovel = imResult.getString("tpimovel").toUpperCase();
                String tend = imResult.getString("end").trim() + ", " + imResult.getString("num").trim() + " " + imResult.getString("compl").trim() ;
                String tsituacao = imResult.getString("situacao").toUpperCase();

                TableControl.add(table, new String[][]{{trgimv, ttpimovel, tend, tsituacao},{"C","C","L","C"}}, true);

            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        DbMain.FecharTabela(imResult);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btFrente;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btImoveis;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btIrPara;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btTras;
    private javax.swing.JCheckBox cbxEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField mAgencia;
    private javax.swing.JTextField mBairro;
    private javax.swing.JTextField mBairroEnv;
    private javax.swing.JTextField mBanco;
    private javax.swing.JTextField mCCorrente;
    private javax.swing.JFormattedTextField mCep;
    private javax.swing.JTextField mCepEnv;
    private javax.swing.JTextField mCidade;
    private javax.swing.JTextField mCidadeEnv;
    private javax.swing.JFormattedTextField mCnpj;
    private javax.swing.JFormattedTextField mCodigo;
    private javax.swing.JTextField mConjugue;
    private javax.swing.JFormattedTextField mCpf;
    private javax.swing.JTextField mCplto;
    private javax.swing.JTextField mCpltoEnv;
    private com.toedter.calendar.JDateChooser mDtEntrada;
    private com.toedter.calendar.JDateChooser mDtNasc;
    private com.toedter.calendar.JDateChooser mDtNascConj;
    private com.toedter.calendar.JDateChooser mDtNascRep;
    private com.toedter.calendar.JDateChooser mDtSaida;
    private javax.swing.JTextField mEmail;
    private javax.swing.JTextField mEndereco;
    private javax.swing.JTextField mEnderecoEnv;
    private javax.swing.JComboBox mEstCivil;
    private javax.swing.JTextField mEstado;
    private javax.swing.JTextField mEstadoEnv;
    private javax.swing.JTextField mFavorecido;
    private javax.swing.JTextField mIdentidade;
    private javax.swing.JTextField mMSgBoleta;
    private javax.swing.JTextField mMsgRecibo;
    private javax.swing.JTextField mNacionalidade;
    private javax.swing.JTextField mNome;
    private javax.swing.JTextField mNumero;
    private javax.swing.JTextField mNumeroEnv;
    private javax.swing.JTextField mObsCaixa;
    private javax.swing.JTextField mProfissao;
    private javax.swing.JTextField mRepresentante;
    private javax.swing.JComboBox mStatus;
    private javax.swing.JTextField mTelefone;
    private javax.swing.JTextField mTipoDoc;
    private javax.swing.JTable tbvImoveis;
    // End of variables declaration//GEN-END:variables

}
